ACADEMIC_ALPHAS = [
    {
        "id": "academic_bab",
        "nickname": "Frazzini-Pedersen 2014 betting-against-beta",
        "theme": ["volatility"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-\\,\\mathrm{ts\\_cov}(r_i, r_m, 252) / \\mathrm{ts\\_std}(r_m, 252)^2\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 252,
        "min_warmup_bars": 253,
    },
    {
        "id": "academic_carhart_mom",
        "nickname": "Carhart 1997 momentum — 12m-1m return",
        "theme": ["momentum"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl((\\mathrm{close}_t - \\mathrm{close}_{t-252})/\\mathrm{close}_{t-252} - (\\mathrm{close}_t - \\mathrm{close}_{t-21})/\\mathrm{close}_{t-21}\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 60,
        "min_warmup_bars": 252,
    },
    {
        "id": "academic_cma",
        "nickname": "[PRICE PROXY] FF2015 CMA — investment via inverse volume growth",
        "theme": ["quality"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-\\Delta_{60}\\log(\\mathrm{ts\\_mean}(\\mathrm{volume},\\,60) + 1)\\bigr)",
        "columns_required": ["volume"],
        "decay_horizon": 60,
        "min_warmup_bars": 120,
    },
    {
        "id": "academic_corr_rewire",
        "nickname": "correlation-rewiring stability score",
        "theme": ["volatility"],
        "formula_latex": "\\mathrm{zscore}_{x}\\Bigl(-\\,\\frac{1}{|J_i|}\\sum_{j \\in J_i}\\bigl|\\rho_{ij}^{\\mathrm{event}} - \\rho_{ij}^{\\mathrm{calm}}\\bigr|\\Bigr),\\quad \\rho^{\\mathrm{event}} = \\mathrm{corr}(r_{t-19..t}),\\ \\rho^{\\mathrm{calm}} = \\mathrm{corr}(r_{t-139..t-20})",
        "columns_required": ["close"],
        "decay_horizon": 60,
        "min_warmup_bars": 142,
    },
    {
        "id": "academic_high52w",
        "nickname": "George-Hwang 2004 52-week-high momentum",
        "theme": ["momentum"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(\\mathrm{close}_t / \\mathrm{ts\\_max}(\\mathrm{close},\\,252)\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 60,
        "min_warmup_bars": 252,
    },
    {
        "id": "academic_hml",
        "nickname": "[PRICE PROXY] FF1993 HML — value via inverse 252d return",
        "theme": ["value"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-(\\mathrm{close}_t - \\mathrm{close}_{t-252}) / \\mathrm{close}_{t-252}\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 60,
        "min_warmup_bars": 252,
    },
    {
        "id": "academic_illiq",
        "nickname": "Amihud 2002 illiquidity — |return| per dollar volume",
        "theme": ["liquidity"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(\\mathrm{ts\\_mean}(|r_t| / (\\mathrm{close}_t \\cdot \\mathrm{volume}_t),\\,21)\\bigr)",
        "columns_required": ["close", "volume"],
        "decay_horizon": 21,
        "min_warmup_bars": 22,
    },
    {
        "id": "academic_mkt_rf",
        "nickname": "[PRICE PROXY] Market factor (Sharpe 1964) — 21d demeaned return",
        "theme": ["momentum"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl((\\mathrm{close}_t - \\mathrm{close}_{t-21}) / \\mathrm{close}_{t-21}\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 21,
        "min_warmup_bars": 21,
    },
    {
        "id": "academic_retskew",
        "nickname": "Harvey-Siddique 2000 return skewness — inverse 60d skew",
        "theme": ["volatility"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-\\mathrm{skew}_{60}(r_t)\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 60,
        "min_warmup_bars": 61,
    },
    {
        "id": "academic_rmw",
        "nickname": "[PRICE PROXY] FF2015 RMW — quality via inverse 60d volatility",
        "theme": ["quality"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-\\mathrm{ts\\_std}((\\mathrm{close}_t - \\mathrm{close}_{t-1}) / \\mathrm{close}_{t-1},\\,60)\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 60,
        "min_warmup_bars": 60,
    },
    {
        "id": "academic_smb",
        "nickname": "[PRICE PROXY] FF1993 SMB — small-minus-big via inverse dollar-volume",
        "theme": ["quality"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-\\log(\\mathrm{ts\\_mean}(\\mathrm{volume} \\cdot \\mathrm{close},\\,60) + 1)\\bigr)",
        "columns_required": ["close", "volume"],
        "decay_horizon": 60,
        "min_warmup_bars": 60,
    },
    {
        "id": "academic_strev",
        "nickname": "Jegadeesh 1990 short-term reversal — inverse 21d return",
        "theme": ["reversal"],
        "formula_latex": "\\mathrm{zscore}_{x}\\bigl(-(\\mathrm{close}_t - \\mathrm{close}_{t-21}) / \\mathrm{close}_{t-21}\\bigr)",
        "columns_required": ["close"],
        "decay_horizon": 21,
        "min_warmup_bars": 21,
    },
]
