# alpha_cfg = Alpha360DL.get_feature_config()

# print(alpha_cfg)


cfg = (
    [
        "Ref($close, 59)/$close",
        "Ref($close, 58)/$close",
        "Ref($close, 57)/$close",
        "Ref($close, 56)/$close",
        "Ref($close, 55)/$close",
        "Ref($close, 54)/$close",
        "Ref($close, 53)/$close",
        "Ref($close, 52)/$close",
        "Ref($close, 51)/$close",
        "Ref($close, 50)/$close",
        "Ref($close, 49)/$close",
        "Ref($close, 48)/$close",
        "Ref($close, 47)/$close",
        "Ref($close, 46)/$close",
        "Ref($close, 45)/$close",
        "Ref($close, 44)/$close",
        "Ref($close, 43)/$close",
        "Ref($close, 42)/$close",
        "Ref($close, 41)/$close",
        "Ref($close, 40)/$close",
        "Ref($close, 39)/$close",
        "Ref($close, 38)/$close",
        "Ref($close, 37)/$close",
        "Ref($close, 36)/$close",
        "Ref($close, 35)/$close",
        "Ref($close, 34)/$close",
        "Ref($close, 33)/$close",
        "Ref($close, 32)/$close",
        "Ref($close, 31)/$close",
        "Ref($close, 30)/$close",
        "Ref($close, 29)/$close",
        "Ref($close, 28)/$close",
        "Ref($close, 27)/$close",
        "Ref($close, 26)/$close",
        "Ref($close, 25)/$close",
        "Ref($close, 24)/$close",
        "Ref($close, 23)/$close",
        "Ref($close, 22)/$close",
        "Ref($close, 21)/$close",
        "Ref($close, 20)/$close",
        "Ref($close, 19)/$close",
        "Ref($close, 18)/$close",
        "Ref($close, 17)/$close",
        "Ref($close, 16)/$close",
        "Ref($close, 15)/$close",
        "Ref($close, 14)/$close",
        "Ref($close, 13)/$close",
        "Ref($close, 12)/$close",
        "Ref($close, 11)/$close",
        "Ref($close, 10)/$close",
        "Ref($close, 9)/$close",
        "Ref($close, 8)/$close",
        "Ref($close, 7)/$close",
        "Ref($close, 6)/$close",
        "Ref($close, 5)/$close",
        "Ref($close, 4)/$close",
        "Ref($close, 3)/$close",
        "Ref($close, 2)/$close",
        "Ref($close, 1)/$close",
        "$close/$close",
        "Ref($open, 59)/$close",
        "Ref($open, 58)/$close",
        "Ref($open, 57)/$close",
        "Ref($open, 56)/$close",
        "Ref($open, 55)/$close",
        "Ref($open, 54)/$close",
        "Ref($open, 53)/$close",
        "Ref($open, 52)/$close",
        "Ref($open, 51)/$close",
        "Ref($open, 50)/$close",
        "Ref($open, 49)/$close",
        "Ref($open, 48)/$close",
        "Ref($open, 47)/$close",
        "Ref($open, 46)/$close",
        "Ref($open, 45)/$close",
        "Ref($open, 44)/$close",
        "Ref($open, 43)/$close",
        "Ref($open, 42)/$close",
        "Ref($open, 41)/$close",
        "Ref($open, 40)/$close",
        "Ref($open, 39)/$close",
        "Ref($open, 38)/$close",
        "Ref($open, 37)/$close",
        "Ref($open, 36)/$close",
        "Ref($open, 35)/$close",
        "Ref($open, 34)/$close",
        "Ref($open, 33)/$close",
        "Ref($open, 32)/$close",
        "Ref($open, 31)/$close",
        "Ref($open, 30)/$close",
        "Ref($open, 29)/$close",
        "Ref($open, 28)/$close",
        "Ref($open, 27)/$close",
        "Ref($open, 26)/$close",
        "Ref($open, 25)/$close",
        "Ref($open, 24)/$close",
        "Ref($open, 23)/$close",
        "Ref($open, 22)/$close",
        "Ref($open, 21)/$close",
        "Ref($open, 20)/$close",
        "Ref($open, 19)/$close",
        "Ref($open, 18)/$close",
        "Ref($open, 17)/$close",
        "Ref($open, 16)/$close",
        "Ref($open, 15)/$close",
        "Ref($open, 14)/$close",
        "Ref($open, 13)/$close",
        "Ref($open, 12)/$close",
        "Ref($open, 11)/$close",
        "Ref($open, 10)/$close",
        "Ref($open, 9)/$close",
        "Ref($open, 8)/$close",
        "Ref($open, 7)/$close",
        "Ref($open, 6)/$close",
        "Ref($open, 5)/$close",
        "Ref($open, 4)/$close",
        "Ref($open, 3)/$close",
        "Ref($open, 2)/$close",
        "Ref($open, 1)/$close",
        "$open/$close",
        "Ref($high, 59)/$close",
        "Ref($high, 58)/$close",
        "Ref($high, 57)/$close",
        "Ref($high, 56)/$close",
        "Ref($high, 55)/$close",
        "Ref($high, 54)/$close",
        "Ref($high, 53)/$close",
        "Ref($high, 52)/$close",
        "Ref($high, 51)/$close",
        "Ref($high, 50)/$close",
        "Ref($high, 49)/$close",
        "Ref($high, 48)/$close",
        "Ref($high, 47)/$close",
        "Ref($high, 46)/$close",
        "Ref($high, 45)/$close",
        "Ref($high, 44)/$close",
        "Ref($high, 43)/$close",
        "Ref($high, 42)/$close",
        "Ref($high, 41)/$close",
        "Ref($high, 40)/$close",
        "Ref($high, 39)/$close",
        "Ref($high, 38)/$close",
        "Ref($high, 37)/$close",
        "Ref($high, 36)/$close",
        "Ref($high, 35)/$close",
        "Ref($high, 34)/$close",
        "Ref($high, 33)/$close",
        "Ref($high, 32)/$close",
        "Ref($high, 31)/$close",
        "Ref($high, 30)/$close",
        "Ref($high, 29)/$close",
        "Ref($high, 28)/$close",
        "Ref($high, 27)/$close",
        "Ref($high, 26)/$close",
        "Ref($high, 25)/$close",
        "Ref($high, 24)/$close",
        "Ref($high, 23)/$close",
        "Ref($high, 22)/$close",
        "Ref($high, 21)/$close",
        "Ref($high, 20)/$close",
        "Ref($high, 19)/$close",
        "Ref($high, 18)/$close",
        "Ref($high, 17)/$close",
        "Ref($high, 16)/$close",
        "Ref($high, 15)/$close",
        "Ref($high, 14)/$close",
        "Ref($high, 13)/$close",
        "Ref($high, 12)/$close",
        "Ref($high, 11)/$close",
        "Ref($high, 10)/$close",
        "Ref($high, 9)/$close",
        "Ref($high, 8)/$close",
        "Ref($high, 7)/$close",
        "Ref($high, 6)/$close",
        "Ref($high, 5)/$close",
        "Ref($high, 4)/$close",
        "Ref($high, 3)/$close",
        "Ref($high, 2)/$close",
        "Ref($high, 1)/$close",
        "$high/$close",
        "Ref($low, 59)/$close",
        "Ref($low, 58)/$close",
        "Ref($low, 57)/$close",
        "Ref($low, 56)/$close",
        "Ref($low, 55)/$close",
        "Ref($low, 54)/$close",
        "Ref($low, 53)/$close",
        "Ref($low, 52)/$close",
        "Ref($low, 51)/$close",
        "Ref($low, 50)/$close",
        "Ref($low, 49)/$close",
        "Ref($low, 48)/$close",
        "Ref($low, 47)/$close",
        "Ref($low, 46)/$close",
        "Ref($low, 45)/$close",
        "Ref($low, 44)/$close",
        "Ref($low, 43)/$close",
        "Ref($low, 42)/$close",
        "Ref($low, 41)/$close",
        "Ref($low, 40)/$close",
        "Ref($low, 39)/$close",
        "Ref($low, 38)/$close",
        "Ref($low, 37)/$close",
        "Ref($low, 36)/$close",
        "Ref($low, 35)/$close",
        "Ref($low, 34)/$close",
        "Ref($low, 33)/$close",
        "Ref($low, 32)/$close",
        "Ref($low, 31)/$close",
        "Ref($low, 30)/$close",
        "Ref($low, 29)/$close",
        "Ref($low, 28)/$close",
        "Ref($low, 27)/$close",
        "Ref($low, 26)/$close",
        "Ref($low, 25)/$close",
        "Ref($low, 24)/$close",
        "Ref($low, 23)/$close",
        "Ref($low, 22)/$close",
        "Ref($low, 21)/$close",
        "Ref($low, 20)/$close",
        "Ref($low, 19)/$close",
        "Ref($low, 18)/$close",
        "Ref($low, 17)/$close",
        "Ref($low, 16)/$close",
        "Ref($low, 15)/$close",
        "Ref($low, 14)/$close",
        "Ref($low, 13)/$close",
        "Ref($low, 12)/$close",
        "Ref($low, 11)/$close",
        "Ref($low, 10)/$close",
        "Ref($low, 9)/$close",
        "Ref($low, 8)/$close",
        "Ref($low, 7)/$close",
        "Ref($low, 6)/$close",
        "Ref($low, 5)/$close",
        "Ref($low, 4)/$close",
        "Ref($low, 3)/$close",
        "Ref($low, 2)/$close",
        "Ref($low, 1)/$close",
        "$low/$close",
        "Ref($vwap, 59)/$close",
        "Ref($vwap, 58)/$close",
        "Ref($vwap, 57)/$close",
        "Ref($vwap, 56)/$close",
        "Ref($vwap, 55)/$close",
        "Ref($vwap, 54)/$close",
        "Ref($vwap, 53)/$close",
        "Ref($vwap, 52)/$close",
        "Ref($vwap, 51)/$close",
        "Ref($vwap, 50)/$close",
        "Ref($vwap, 49)/$close",
        "Ref($vwap, 48)/$close",
        "Ref($vwap, 47)/$close",
        "Ref($vwap, 46)/$close",
        "Ref($vwap, 45)/$close",
        "Ref($vwap, 44)/$close",
        "Ref($vwap, 43)/$close",
        "Ref($vwap, 42)/$close",
        "Ref($vwap, 41)/$close",
        "Ref($vwap, 40)/$close",
        "Ref($vwap, 39)/$close",
        "Ref($vwap, 38)/$close",
        "Ref($vwap, 37)/$close",
        "Ref($vwap, 36)/$close",
        "Ref($vwap, 35)/$close",
        "Ref($vwap, 34)/$close",
        "Ref($vwap, 33)/$close",
        "Ref($vwap, 32)/$close",
        "Ref($vwap, 31)/$close",
        "Ref($vwap, 30)/$close",
        "Ref($vwap, 29)/$close",
        "Ref($vwap, 28)/$close",
        "Ref($vwap, 27)/$close",
        "Ref($vwap, 26)/$close",
        "Ref($vwap, 25)/$close",
        "Ref($vwap, 24)/$close",
        "Ref($vwap, 23)/$close",
        "Ref($vwap, 22)/$close",
        "Ref($vwap, 21)/$close",
        "Ref($vwap, 20)/$close",
        "Ref($vwap, 19)/$close",
        "Ref($vwap, 18)/$close",
        "Ref($vwap, 17)/$close",
        "Ref($vwap, 16)/$close",
        "Ref($vwap, 15)/$close",
        "Ref($vwap, 14)/$close",
        "Ref($vwap, 13)/$close",
        "Ref($vwap, 12)/$close",
        "Ref($vwap, 11)/$close",
        "Ref($vwap, 10)/$close",
        "Ref($vwap, 9)/$close",
        "Ref($vwap, 8)/$close",
        "Ref($vwap, 7)/$close",
        "Ref($vwap, 6)/$close",
        "Ref($vwap, 5)/$close",
        "Ref($vwap, 4)/$close",
        "Ref($vwap, 3)/$close",
        "Ref($vwap, 2)/$close",
        "Ref($vwap, 1)/$close",
        "$vwap/$close",
        "Ref($volume, 59)/($volume+1e-12)",
        "Ref($volume, 58)/($volume+1e-12)",
        "Ref($volume, 57)/($volume+1e-12)",
        "Ref($volume, 56)/($volume+1e-12)",
        "Ref($volume, 55)/($volume+1e-12)",
        "Ref($volume, 54)/($volume+1e-12)",
        "Ref($volume, 53)/($volume+1e-12)",
        "Ref($volume, 52)/($volume+1e-12)",
        "Ref($volume, 51)/($volume+1e-12)",
        "Ref($volume, 50)/($volume+1e-12)",
        "Ref($volume, 49)/($volume+1e-12)",
        "Ref($volume, 48)/($volume+1e-12)",
        "Ref($volume, 47)/($volume+1e-12)",
        "Ref($volume, 46)/($volume+1e-12)",
        "Ref($volume, 45)/($volume+1e-12)",
        "Ref($volume, 44)/($volume+1e-12)",
        "Ref($volume, 43)/($volume+1e-12)",
        "Ref($volume, 42)/($volume+1e-12)",
        "Ref($volume, 41)/($volume+1e-12)",
        "Ref($volume, 40)/($volume+1e-12)",
        "Ref($volume, 39)/($volume+1e-12)",
        "Ref($volume, 38)/($volume+1e-12)",
        "Ref($volume, 37)/($volume+1e-12)",
        "Ref($volume, 36)/($volume+1e-12)",
        "Ref($volume, 35)/($volume+1e-12)",
        "Ref($volume, 34)/($volume+1e-12)",
        "Ref($volume, 33)/($volume+1e-12)",
        "Ref($volume, 32)/($volume+1e-12)",
        "Ref($volume, 31)/($volume+1e-12)",
        "Ref($volume, 30)/($volume+1e-12)",
        "Ref($volume, 29)/($volume+1e-12)",
        "Ref($volume, 28)/($volume+1e-12)",
        "Ref($volume, 27)/($volume+1e-12)",
        "Ref($volume, 26)/($volume+1e-12)",
        "Ref($volume, 25)/($volume+1e-12)",
        "Ref($volume, 24)/($volume+1e-12)",
        "Ref($volume, 23)/($volume+1e-12)",
        "Ref($volume, 22)/($volume+1e-12)",
        "Ref($volume, 21)/($volume+1e-12)",
        "Ref($volume, 20)/($volume+1e-12)",
        "Ref($volume, 19)/($volume+1e-12)",
        "Ref($volume, 18)/($volume+1e-12)",
        "Ref($volume, 17)/($volume+1e-12)",
        "Ref($volume, 16)/($volume+1e-12)",
        "Ref($volume, 15)/($volume+1e-12)",
        "Ref($volume, 14)/($volume+1e-12)",
        "Ref($volume, 13)/($volume+1e-12)",
        "Ref($volume, 12)/($volume+1e-12)",
        "Ref($volume, 11)/($volume+1e-12)",
        "Ref($volume, 10)/($volume+1e-12)",
        "Ref($volume, 9)/($volume+1e-12)",
        "Ref($volume, 8)/($volume+1e-12)",
        "Ref($volume, 7)/($volume+1e-12)",
        "Ref($volume, 6)/($volume+1e-12)",
        "Ref($volume, 5)/($volume+1e-12)",
        "Ref($volume, 4)/($volume+1e-12)",
        "Ref($volume, 3)/($volume+1e-12)",
        "Ref($volume, 2)/($volume+1e-12)",
        "Ref($volume, 1)/($volume+1e-12)",
        "$volume/($volume+1e-12)",
    ],
    [
        "CLOSE59",
        "CLOSE58",
        "CLOSE57",
        "CLOSE56",
        "CLOSE55",
        "CLOSE54",
        "CLOSE53",
        "CLOSE52",
        "CLOSE51",
        "CLOSE50",
        "CLOSE49",
        "CLOSE48",
        "CLOSE47",
        "CLOSE46",
        "CLOSE45",
        "CLOSE44",
        "CLOSE43",
        "CLOSE42",
        "CLOSE41",
        "CLOSE40",
        "CLOSE39",
        "CLOSE38",
        "CLOSE37",
        "CLOSE36",
        "CLOSE35",
        "CLOSE34",
        "CLOSE33",
        "CLOSE32",
        "CLOSE31",
        "CLOSE30",
        "CLOSE29",
        "CLOSE28",
        "CLOSE27",
        "CLOSE26",
        "CLOSE25",
        "CLOSE24",
        "CLOSE23",
        "CLOSE22",
        "CLOSE21",
        "CLOSE20",
        "CLOSE19",
        "CLOSE18",
        "CLOSE17",
        "CLOSE16",
        "CLOSE15",
        "CLOSE14",
        "CLOSE13",
        "CLOSE12",
        "CLOSE11",
        "CLOSE10",
        "CLOSE9",
        "CLOSE8",
        "CLOSE7",
        "CLOSE6",
        "CLOSE5",
        "CLOSE4",
        "CLOSE3",
        "CLOSE2",
        "CLOSE1",
        "CLOSE0",
        "OPEN59",
        "OPEN58",
        "OPEN57",
        "OPEN56",
        "OPEN55",
        "OPEN54",
        "OPEN53",
        "OPEN52",
        "OPEN51",
        "OPEN50",
        "OPEN49",
        "OPEN48",
        "OPEN47",
        "OPEN46",
        "OPEN45",
        "OPEN44",
        "OPEN43",
        "OPEN42",
        "OPEN41",
        "OPEN40",
        "OPEN39",
        "OPEN38",
        "OPEN37",
        "OPEN36",
        "OPEN35",
        "OPEN34",
        "OPEN33",
        "OPEN32",
        "OPEN31",
        "OPEN30",
        "OPEN29",
        "OPEN28",
        "OPEN27",
        "OPEN26",
        "OPEN25",
        "OPEN24",
        "OPEN23",
        "OPEN22",
        "OPEN21",
        "OPEN20",
        "OPEN19",
        "OPEN18",
        "OPEN17",
        "OPEN16",
        "OPEN15",
        "OPEN14",
        "OPEN13",
        "OPEN12",
        "OPEN11",
        "OPEN10",
        "OPEN9",
        "OPEN8",
        "OPEN7",
        "OPEN6",
        "OPEN5",
        "OPEN4",
        "OPEN3",
        "OPEN2",
        "OPEN1",
        "OPEN0",
        "HIGH59",
        "HIGH58",
        "HIGH57",
        "HIGH56",
        "HIGH55",
        "HIGH54",
        "HIGH53",
        "HIGH52",
        "HIGH51",
        "HIGH50",
        "HIGH49",
        "HIGH48",
        "HIGH47",
        "HIGH46",
        "HIGH45",
        "HIGH44",
        "HIGH43",
        "HIGH42",
        "HIGH41",
        "HIGH40",
        "HIGH39",
        "HIGH38",
        "HIGH37",
        "HIGH36",
        "HIGH35",
        "HIGH34",
        "HIGH33",
        "HIGH32",
        "HIGH31",
        "HIGH30",
        "HIGH29",
        "HIGH28",
        "HIGH27",
        "HIGH26",
        "HIGH25",
        "HIGH24",
        "HIGH23",
        "HIGH22",
        "HIGH21",
        "HIGH20",
        "HIGH19",
        "HIGH18",
        "HIGH17",
        "HIGH16",
        "HIGH15",
        "HIGH14",
        "HIGH13",
        "HIGH12",
        "HIGH11",
        "HIGH10",
        "HIGH9",
        "HIGH8",
        "HIGH7",
        "HIGH6",
        "HIGH5",
        "HIGH4",
        "HIGH3",
        "HIGH2",
        "HIGH1",
        "HIGH0",
        "LOW59",
        "LOW58",
        "LOW57",
        "LOW56",
        "LOW55",
        "LOW54",
        "LOW53",
        "LOW52",
        "LOW51",
        "LOW50",
        "LOW49",
        "LOW48",
        "LOW47",
        "LOW46",
        "LOW45",
        "LOW44",
        "LOW43",
        "LOW42",
        "LOW41",
        "LOW40",
        "LOW39",
        "LOW38",
        "LOW37",
        "LOW36",
        "LOW35",
        "LOW34",
        "LOW33",
        "LOW32",
        "LOW31",
        "LOW30",
        "LOW29",
        "LOW28",
        "LOW27",
        "LOW26",
        "LOW25",
        "LOW24",
        "LOW23",
        "LOW22",
        "LOW21",
        "LOW20",
        "LOW19",
        "LOW18",
        "LOW17",
        "LOW16",
        "LOW15",
        "LOW14",
        "LOW13",
        "LOW12",
        "LOW11",
        "LOW10",
        "LOW9",
        "LOW8",
        "LOW7",
        "LOW6",
        "LOW5",
        "LOW4",
        "LOW3",
        "LOW2",
        "LOW1",
        "LOW0",
        "VWAP59",
        "VWAP58",
        "VWAP57",
        "VWAP56",
        "VWAP55",
        "VWAP54",
        "VWAP53",
        "VWAP52",
        "VWAP51",
        "VWAP50",
        "VWAP49",
        "VWAP48",
        "VWAP47",
        "VWAP46",
        "VWAP45",
        "VWAP44",
        "VWAP43",
        "VWAP42",
        "VWAP41",
        "VWAP40",
        "VWAP39",
        "VWAP38",
        "VWAP37",
        "VWAP36",
        "VWAP35",
        "VWAP34",
        "VWAP33",
        "VWAP32",
        "VWAP31",
        "VWAP30",
        "VWAP29",
        "VWAP28",
        "VWAP27",
        "VWAP26",
        "VWAP25",
        "VWAP24",
        "VWAP23",
        "VWAP22",
        "VWAP21",
        "VWAP20",
        "VWAP19",
        "VWAP18",
        "VWAP17",
        "VWAP16",
        "VWAP15",
        "VWAP14",
        "VWAP13",
        "VWAP12",
        "VWAP11",
        "VWAP10",
        "VWAP9",
        "VWAP8",
        "VWAP7",
        "VWAP6",
        "VWAP5",
        "VWAP4",
        "VWAP3",
        "VWAP2",
        "VWAP1",
        "VWAP0",
        "VOLUME59",
        "VOLUME58",
        "VOLUME57",
        "VOLUME56",
        "VOLUME55",
        "VOLUME54",
        "VOLUME53",
        "VOLUME52",
        "VOLUME51",
        "VOLUME50",
        "VOLUME49",
        "VOLUME48",
        "VOLUME47",
        "VOLUME46",
        "VOLUME45",
        "VOLUME44",
        "VOLUME43",
        "VOLUME42",
        "VOLUME41",
        "VOLUME40",
        "VOLUME39",
        "VOLUME38",
        "VOLUME37",
        "VOLUME36",
        "VOLUME35",
        "VOLUME34",
        "VOLUME33",
        "VOLUME32",
        "VOLUME31",
        "VOLUME30",
        "VOLUME29",
        "VOLUME28",
        "VOLUME27",
        "VOLUME26",
        "VOLUME25",
        "VOLUME24",
        "VOLUME23",
        "VOLUME22",
        "VOLUME21",
        "VOLUME20",
        "VOLUME19",
        "VOLUME18",
        "VOLUME17",
        "VOLUME16",
        "VOLUME15",
        "VOLUME14",
        "VOLUME13",
        "VOLUME12",
        "VOLUME11",
        "VOLUME10",
        "VOLUME9",
        "VOLUME8",
        "VOLUME7",
        "VOLUME6",
        "VOLUME5",
        "VOLUME4",
        "VOLUME3",
        "VOLUME2",
        "VOLUME1",
        "VOLUME0",
    ],
)

assert len(cfg[0]) == len(cfg[1])
cfg_dict = [
    {"formula": formula, "name": f"qlib360_{name}"}
    for formula, name in zip(cfg[0], cfg[1])
]

print(cfg_dict)

# alpha_cfg = Alpha158DL.get_feature_config()

# print(alpha_cfg)

cfg158 = (
    [
        "($close-$open)/$open",
        "($high-$low)/$open",
        "($close-$open)/($high-$low+1e-12)",
        "($high-Greater($open, $close))/$open",
        "($high-Greater($open, $close))/($high-$low+1e-12)",
        "(Less($open, $close)-$low)/$open",
        "(Less($open, $close)-$low)/($high-$low+1e-12)",
        "(2*$close-$high-$low)/$open",
        "(2*$close-$high-$low)/($high-$low+1e-12)",
        "$open/$close",
        "$high/$close",
        "$low/$close",
        "$vwap/$close",
        "Ref($close, 5)/$close",
        "Ref($close, 10)/$close",
        "Ref($close, 20)/$close",
        "Ref($close, 30)/$close",
        "Ref($close, 60)/$close",
        "Mean($close, 5)/$close",
        "Mean($close, 10)/$close",
        "Mean($close, 20)/$close",
        "Mean($close, 30)/$close",
        "Mean($close, 60)/$close",
        "Std($close, 5)/$close",
        "Std($close, 10)/$close",
        "Std($close, 20)/$close",
        "Std($close, 30)/$close",
        "Std($close, 60)/$close",
        "Slope($close, 5)/$close",
        "Slope($close, 10)/$close",
        "Slope($close, 20)/$close",
        "Slope($close, 30)/$close",
        "Slope($close, 60)/$close",
        "Rsquare($close, 5)",
        "Rsquare($close, 10)",
        "Rsquare($close, 20)",
        "Rsquare($close, 30)",
        "Rsquare($close, 60)",
        "Resi($close, 5)/$close",
        "Resi($close, 10)/$close",
        "Resi($close, 20)/$close",
        "Resi($close, 30)/$close",
        "Resi($close, 60)/$close",
        "Max($high, 5)/$close",
        "Max($high, 10)/$close",
        "Max($high, 20)/$close",
        "Max($high, 30)/$close",
        "Max($high, 60)/$close",
        "Min($low, 5)/$close",
        "Min($low, 10)/$close",
        "Min($low, 20)/$close",
        "Min($low, 30)/$close",
        "Min($low, 60)/$close",
        "Quantile($close, 5, 0.8)/$close",
        "Quantile($close, 10, 0.8)/$close",
        "Quantile($close, 20, 0.8)/$close",
        "Quantile($close, 30, 0.8)/$close",
        "Quantile($close, 60, 0.8)/$close",
        "Quantile($close, 5, 0.2)/$close",
        "Quantile($close, 10, 0.2)/$close",
        "Quantile($close, 20, 0.2)/$close",
        "Quantile($close, 30, 0.2)/$close",
        "Quantile($close, 60, 0.2)/$close",
        "Rank($close, 5)",
        "Rank($close, 10)",
        "Rank($close, 20)",
        "Rank($close, 30)",
        "Rank($close, 60)",
        "($close-Min($low, 5))/(Max($high, 5)-Min($low, 5)+1e-12)",
        "($close-Min($low, 10))/(Max($high, 10)-Min($low, 10)+1e-12)",
        "($close-Min($low, 20))/(Max($high, 20)-Min($low, 20)+1e-12)",
        "($close-Min($low, 30))/(Max($high, 30)-Min($low, 30)+1e-12)",
        "($close-Min($low, 60))/(Max($high, 60)-Min($low, 60)+1e-12)",
        "IdxMax($high, 5)/5",
        "IdxMax($high, 10)/10",
        "IdxMax($high, 20)/20",
        "IdxMax($high, 30)/30",
        "IdxMax($high, 60)/60",
        "IdxMin($low, 5)/5",
        "IdxMin($low, 10)/10",
        "IdxMin($low, 20)/20",
        "IdxMin($low, 30)/30",
        "IdxMin($low, 60)/60",
        "(IdxMax($high, 5)-IdxMin($low, 5))/5",
        "(IdxMax($high, 10)-IdxMin($low, 10))/10",
        "(IdxMax($high, 20)-IdxMin($low, 20))/20",
        "(IdxMax($high, 30)-IdxMin($low, 30))/30",
        "(IdxMax($high, 60)-IdxMin($low, 60))/60",
        "Corr($close, Log($volume+1), 5)",
        "Corr($close, Log($volume+1), 10)",
        "Corr($close, Log($volume+1), 20)",
        "Corr($close, Log($volume+1), 30)",
        "Corr($close, Log($volume+1), 60)",
        "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 5)",
        "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 10)",
        "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 20)",
        "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 30)",
        "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 60)",
        "Mean($close>Ref($close, 1), 5)",
        "Mean($close>Ref($close, 1), 10)",
        "Mean($close>Ref($close, 1), 20)",
        "Mean($close>Ref($close, 1), 30)",
        "Mean($close>Ref($close, 1), 60)",
        "Mean($close<Ref($close, 1), 5)",
        "Mean($close<Ref($close, 1), 10)",
        "Mean($close<Ref($close, 1), 20)",
        "Mean($close<Ref($close, 1), 30)",
        "Mean($close<Ref($close, 1), 60)",
        "Mean($close>Ref($close, 1), 5)-Mean($close<Ref($close, 1), 5)",
        "Mean($close>Ref($close, 1), 10)-Mean($close<Ref($close, 1), 10)",
        "Mean($close>Ref($close, 1), 20)-Mean($close<Ref($close, 1), 20)",
        "Mean($close>Ref($close, 1), 30)-Mean($close<Ref($close, 1), 30)",
        "Mean($close>Ref($close, 1), 60)-Mean($close<Ref($close, 1), 60)",
        "Sum(Greater($close-Ref($close, 1), 0), 5)/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "Sum(Greater($close-Ref($close, 1), 0), 10)/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "Sum(Greater($close-Ref($close, 1), 0), 20)/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "Sum(Greater($close-Ref($close, 1), 0), 30)/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "Sum(Greater($close-Ref($close, 1), 0), 60)/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "Sum(Greater(Ref($close, 1)-$close, 0), 5)/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "Sum(Greater(Ref($close, 1)-$close, 0), 10)/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "Sum(Greater(Ref($close, 1)-$close, 0), 20)/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "Sum(Greater(Ref($close, 1)-$close, 0), 30)/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "Sum(Greater(Ref($close, 1)-$close, 0), 60)/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "(Sum(Greater($close-Ref($close, 1), 0), 5)-Sum(Greater(Ref($close, 1)-$close, 0), 5))/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "(Sum(Greater($close-Ref($close, 1), 0), 10)-Sum(Greater(Ref($close, 1)-$close, 0), 10))/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "(Sum(Greater($close-Ref($close, 1), 0), 20)-Sum(Greater(Ref($close, 1)-$close, 0), 20))/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "(Sum(Greater($close-Ref($close, 1), 0), 30)-Sum(Greater(Ref($close, 1)-$close, 0), 30))/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "(Sum(Greater($close-Ref($close, 1), 0), 60)-Sum(Greater(Ref($close, 1)-$close, 0), 60))/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "Mean($volume, 5)/($volume+1e-12)",
        "Mean($volume, 10)/($volume+1e-12)",
        "Mean($volume, 20)/($volume+1e-12)",
        "Mean($volume, 30)/($volume+1e-12)",
        "Mean($volume, 60)/($volume+1e-12)",
        "Std($volume, 5)/($volume+1e-12)",
        "Std($volume, 10)/($volume+1e-12)",
        "Std($volume, 20)/($volume+1e-12)",
        "Std($volume, 30)/($volume+1e-12)",
        "Std($volume, 60)/($volume+1e-12)",
        "Std(Abs($close/Ref($close, 1)-1)*$volume, 5)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 5)+1e-12)",
        "Std(Abs($close/Ref($close, 1)-1)*$volume, 10)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 10)+1e-12)",
        "Std(Abs($close/Ref($close, 1)-1)*$volume, 20)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 20)+1e-12)",
        "Std(Abs($close/Ref($close, 1)-1)*$volume, 30)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 30)+1e-12)",
        "Std(Abs($close/Ref($close, 1)-1)*$volume, 60)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 60)+1e-12)",
        "Sum(Greater($volume-Ref($volume, 1), 0), 5)/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "Sum(Greater($volume-Ref($volume, 1), 0), 10)/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "Sum(Greater($volume-Ref($volume, 1), 0), 20)/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "Sum(Greater($volume-Ref($volume, 1), 0), 30)/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "Sum(Greater($volume-Ref($volume, 1), 0), 60)/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "Sum(Greater(Ref($volume, 1)-$volume, 0), 5)/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "Sum(Greater(Ref($volume, 1)-$volume, 0), 10)/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "Sum(Greater(Ref($volume, 1)-$volume, 0), 20)/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "Sum(Greater(Ref($volume, 1)-$volume, 0), 30)/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "Sum(Greater(Ref($volume, 1)-$volume, 0), 60)/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "(Sum(Greater($volume-Ref($volume, 1), 0), 5)-Sum(Greater(Ref($volume, 1)-$volume, 0), 5))/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "(Sum(Greater($volume-Ref($volume, 1), 0), 10)-Sum(Greater(Ref($volume, 1)-$volume, 0), 10))/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "(Sum(Greater($volume-Ref($volume, 1), 0), 20)-Sum(Greater(Ref($volume, 1)-$volume, 0), 20))/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "(Sum(Greater($volume-Ref($volume, 1), 0), 30)-Sum(Greater(Ref($volume, 1)-$volume, 0), 30))/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "(Sum(Greater($volume-Ref($volume, 1), 0), 60)-Sum(Greater(Ref($volume, 1)-$volume, 0), 60))/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
    ],
    [
        "KMID",
        "KLEN",
        "KMID2",
        "KUP",
        "KUP2",
        "KLOW",
        "KLOW2",
        "KSFT",
        "KSFT2",
        "OPEN0",
        "HIGH0",
        "LOW0",
        "VWAP0",
        "ROC5",
        "ROC10",
        "ROC20",
        "ROC30",
        "ROC60",
        "MA5",
        "MA10",
        "MA20",
        "MA30",
        "MA60",
        "STD5",
        "STD10",
        "STD20",
        "STD30",
        "STD60",
        "BETA5",
        "BETA10",
        "BETA20",
        "BETA30",
        "BETA60",
        "RSQR5",
        "RSQR10",
        "RSQR20",
        "RSQR30",
        "RSQR60",
        "RESI5",
        "RESI10",
        "RESI20",
        "RESI30",
        "RESI60",
        "MAX5",
        "MAX10",
        "MAX20",
        "MAX30",
        "MAX60",
        "MIN5",
        "MIN10",
        "MIN20",
        "MIN30",
        "MIN60",
        "QTLU5",
        "QTLU10",
        "QTLU20",
        "QTLU30",
        "QTLU60",
        "QTLD5",
        "QTLD10",
        "QTLD20",
        "QTLD30",
        "QTLD60",
        "RANK5",
        "RANK10",
        "RANK20",
        "RANK30",
        "RANK60",
        "RSV5",
        "RSV10",
        "RSV20",
        "RSV30",
        "RSV60",
        "IMAX5",
        "IMAX10",
        "IMAX20",
        "IMAX30",
        "IMAX60",
        "IMIN5",
        "IMIN10",
        "IMIN20",
        "IMIN30",
        "IMIN60",
        "IMXD5",
        "IMXD10",
        "IMXD20",
        "IMXD30",
        "IMXD60",
        "CORR5",
        "CORR10",
        "CORR20",
        "CORR30",
        "CORR60",
        "CORD5",
        "CORD10",
        "CORD20",
        "CORD30",
        "CORD60",
        "CNTP5",
        "CNTP10",
        "CNTP20",
        "CNTP30",
        "CNTP60",
        "CNTN5",
        "CNTN10",
        "CNTN20",
        "CNTN30",
        "CNTN60",
        "CNTD5",
        "CNTD10",
        "CNTD20",
        "CNTD30",
        "CNTD60",
        "SUMP5",
        "SUMP10",
        "SUMP20",
        "SUMP30",
        "SUMP60",
        "SUMN5",
        "SUMN10",
        "SUMN20",
        "SUMN30",
        "SUMN60",
        "SUMD5",
        "SUMD10",
        "SUMD20",
        "SUMD30",
        "SUMD60",
        "VMA5",
        "VMA10",
        "VMA20",
        "VMA30",
        "VMA60",
        "VSTD5",
        "VSTD10",
        "VSTD20",
        "VSTD30",
        "VSTD60",
        "WVMA5",
        "WVMA10",
        "WVMA20",
        "WVMA30",
        "WVMA60",
        "VSUMP5",
        "VSUMP10",
        "VSUMP20",
        "VSUMP30",
        "VSUMP60",
        "VSUMN5",
        "VSUMN10",
        "VSUMN20",
        "VSUMN30",
        "VSUMN60",
        "VSUMD5",
        "VSUMD10",
        "VSUMD20",
        "VSUMD30",
        "VSUMD60",
    ],
)


assert len(cfg158[0]) == len(cfg158[1])
cfg_dict2 = [
    {"formula": formula, "name": f"qlib158_{name}"}
    for formula, name in zip(cfg158[0], cfg158[1])
]

print(cfg_dict2)


qlib_alpha360 = [
    {"formula": "Ref($close, 59)/$close", "name": "qlib360_CLOSE59"},
    {"formula": "Ref($close, 58)/$close", "name": "qlib360_CLOSE58"},
    {"formula": "Ref($close, 57)/$close", "name": "qlib360_CLOSE57"},
    {"formula": "Ref($close, 56)/$close", "name": "qlib360_CLOSE56"},
    {"formula": "Ref($close, 55)/$close", "name": "qlib360_CLOSE55"},
    {"formula": "Ref($close, 54)/$close", "name": "qlib360_CLOSE54"},
    {"formula": "Ref($close, 53)/$close", "name": "qlib360_CLOSE53"},
    {"formula": "Ref($close, 52)/$close", "name": "qlib360_CLOSE52"},
    {"formula": "Ref($close, 51)/$close", "name": "qlib360_CLOSE51"},
    {"formula": "Ref($close, 50)/$close", "name": "qlib360_CLOSE50"},
    {"formula": "Ref($close, 49)/$close", "name": "qlib360_CLOSE49"},
    {"formula": "Ref($close, 48)/$close", "name": "qlib360_CLOSE48"},
    {"formula": "Ref($close, 47)/$close", "name": "qlib360_CLOSE47"},
    {"formula": "Ref($close, 46)/$close", "name": "qlib360_CLOSE46"},
    {"formula": "Ref($close, 45)/$close", "name": "qlib360_CLOSE45"},
    {"formula": "Ref($close, 44)/$close", "name": "qlib360_CLOSE44"},
    {"formula": "Ref($close, 43)/$close", "name": "qlib360_CLOSE43"},
    {"formula": "Ref($close, 42)/$close", "name": "qlib360_CLOSE42"},
    {"formula": "Ref($close, 41)/$close", "name": "qlib360_CLOSE41"},
    {"formula": "Ref($close, 40)/$close", "name": "qlib360_CLOSE40"},
    {"formula": "Ref($close, 39)/$close", "name": "qlib360_CLOSE39"},
    {"formula": "Ref($close, 38)/$close", "name": "qlib360_CLOSE38"},
    {"formula": "Ref($close, 37)/$close", "name": "qlib360_CLOSE37"},
    {"formula": "Ref($close, 36)/$close", "name": "qlib360_CLOSE36"},
    {"formula": "Ref($close, 35)/$close", "name": "qlib360_CLOSE35"},
    {"formula": "Ref($close, 34)/$close", "name": "qlib360_CLOSE34"},
    {"formula": "Ref($close, 33)/$close", "name": "qlib360_CLOSE33"},
    {"formula": "Ref($close, 32)/$close", "name": "qlib360_CLOSE32"},
    {"formula": "Ref($close, 31)/$close", "name": "qlib360_CLOSE31"},
    {"formula": "Ref($close, 30)/$close", "name": "qlib360_CLOSE30"},
    {"formula": "Ref($close, 29)/$close", "name": "qlib360_CLOSE29"},
    {"formula": "Ref($close, 28)/$close", "name": "qlib360_CLOSE28"},
    {"formula": "Ref($close, 27)/$close", "name": "qlib360_CLOSE27"},
    {"formula": "Ref($close, 26)/$close", "name": "qlib360_CLOSE26"},
    {"formula": "Ref($close, 25)/$close", "name": "qlib360_CLOSE25"},
    {"formula": "Ref($close, 24)/$close", "name": "qlib360_CLOSE24"},
    {"formula": "Ref($close, 23)/$close", "name": "qlib360_CLOSE23"},
    {"formula": "Ref($close, 22)/$close", "name": "qlib360_CLOSE22"},
    {"formula": "Ref($close, 21)/$close", "name": "qlib360_CLOSE21"},
    {"formula": "Ref($close, 20)/$close", "name": "qlib360_CLOSE20"},
    {"formula": "Ref($close, 19)/$close", "name": "qlib360_CLOSE19"},
    {"formula": "Ref($close, 18)/$close", "name": "qlib360_CLOSE18"},
    {"formula": "Ref($close, 17)/$close", "name": "qlib360_CLOSE17"},
    {"formula": "Ref($close, 16)/$close", "name": "qlib360_CLOSE16"},
    {"formula": "Ref($close, 15)/$close", "name": "qlib360_CLOSE15"},
    {"formula": "Ref($close, 14)/$close", "name": "qlib360_CLOSE14"},
    {"formula": "Ref($close, 13)/$close", "name": "qlib360_CLOSE13"},
    {"formula": "Ref($close, 12)/$close", "name": "qlib360_CLOSE12"},
    {"formula": "Ref($close, 11)/$close", "name": "qlib360_CLOSE11"},
    {"formula": "Ref($close, 10)/$close", "name": "qlib360_CLOSE10"},
    {"formula": "Ref($close, 9)/$close", "name": "qlib360_CLOSE9"},
    {"formula": "Ref($close, 8)/$close", "name": "qlib360_CLOSE8"},
    {"formula": "Ref($close, 7)/$close", "name": "qlib360_CLOSE7"},
    {"formula": "Ref($close, 6)/$close", "name": "qlib360_CLOSE6"},
    {"formula": "Ref($close, 5)/$close", "name": "qlib360_CLOSE5"},
    {"formula": "Ref($close, 4)/$close", "name": "qlib360_CLOSE4"},
    {"formula": "Ref($close, 3)/$close", "name": "qlib360_CLOSE3"},
    {"formula": "Ref($close, 2)/$close", "name": "qlib360_CLOSE2"},
    {"formula": "Ref($close, 1)/$close", "name": "qlib360_CLOSE1"},
    {"formula": "$close/$close", "name": "qlib360_CLOSE0"},
    {"formula": "Ref($open, 59)/$close", "name": "qlib360_OPEN59"},
    {"formula": "Ref($open, 58)/$close", "name": "qlib360_OPEN58"},
    {"formula": "Ref($open, 57)/$close", "name": "qlib360_OPEN57"},
    {"formula": "Ref($open, 56)/$close", "name": "qlib360_OPEN56"},
    {"formula": "Ref($open, 55)/$close", "name": "qlib360_OPEN55"},
    {"formula": "Ref($open, 54)/$close", "name": "qlib360_OPEN54"},
    {"formula": "Ref($open, 53)/$close", "name": "qlib360_OPEN53"},
    {"formula": "Ref($open, 52)/$close", "name": "qlib360_OPEN52"},
    {"formula": "Ref($open, 51)/$close", "name": "qlib360_OPEN51"},
    {"formula": "Ref($open, 50)/$close", "name": "qlib360_OPEN50"},
    {"formula": "Ref($open, 49)/$close", "name": "qlib360_OPEN49"},
    {"formula": "Ref($open, 48)/$close", "name": "qlib360_OPEN48"},
    {"formula": "Ref($open, 47)/$close", "name": "qlib360_OPEN47"},
    {"formula": "Ref($open, 46)/$close", "name": "qlib360_OPEN46"},
    {"formula": "Ref($open, 45)/$close", "name": "qlib360_OPEN45"},
    {"formula": "Ref($open, 44)/$close", "name": "qlib360_OPEN44"},
    {"formula": "Ref($open, 43)/$close", "name": "qlib360_OPEN43"},
    {"formula": "Ref($open, 42)/$close", "name": "qlib360_OPEN42"},
    {"formula": "Ref($open, 41)/$close", "name": "qlib360_OPEN41"},
    {"formula": "Ref($open, 40)/$close", "name": "qlib360_OPEN40"},
    {"formula": "Ref($open, 39)/$close", "name": "qlib360_OPEN39"},
    {"formula": "Ref($open, 38)/$close", "name": "qlib360_OPEN38"},
    {"formula": "Ref($open, 37)/$close", "name": "qlib360_OPEN37"},
    {"formula": "Ref($open, 36)/$close", "name": "qlib360_OPEN36"},
    {"formula": "Ref($open, 35)/$close", "name": "qlib360_OPEN35"},
    {"formula": "Ref($open, 34)/$close", "name": "qlib360_OPEN34"},
    {"formula": "Ref($open, 33)/$close", "name": "qlib360_OPEN33"},
    {"formula": "Ref($open, 32)/$close", "name": "qlib360_OPEN32"},
    {"formula": "Ref($open, 31)/$close", "name": "qlib360_OPEN31"},
    {"formula": "Ref($open, 30)/$close", "name": "qlib360_OPEN30"},
    {"formula": "Ref($open, 29)/$close", "name": "qlib360_OPEN29"},
    {"formula": "Ref($open, 28)/$close", "name": "qlib360_OPEN28"},
    {"formula": "Ref($open, 27)/$close", "name": "qlib360_OPEN27"},
    {"formula": "Ref($open, 26)/$close", "name": "qlib360_OPEN26"},
    {"formula": "Ref($open, 25)/$close", "name": "qlib360_OPEN25"},
    {"formula": "Ref($open, 24)/$close", "name": "qlib360_OPEN24"},
    {"formula": "Ref($open, 23)/$close", "name": "qlib360_OPEN23"},
    {"formula": "Ref($open, 22)/$close", "name": "qlib360_OPEN22"},
    {"formula": "Ref($open, 21)/$close", "name": "qlib360_OPEN21"},
    {"formula": "Ref($open, 20)/$close", "name": "qlib360_OPEN20"},
    {"formula": "Ref($open, 19)/$close", "name": "qlib360_OPEN19"},
    {"formula": "Ref($open, 18)/$close", "name": "qlib360_OPEN18"},
    {"formula": "Ref($open, 17)/$close", "name": "qlib360_OPEN17"},
    {"formula": "Ref($open, 16)/$close", "name": "qlib360_OPEN16"},
    {"formula": "Ref($open, 15)/$close", "name": "qlib360_OPEN15"},
    {"formula": "Ref($open, 14)/$close", "name": "qlib360_OPEN14"},
    {"formula": "Ref($open, 13)/$close", "name": "qlib360_OPEN13"},
    {"formula": "Ref($open, 12)/$close", "name": "qlib360_OPEN12"},
    {"formula": "Ref($open, 11)/$close", "name": "qlib360_OPEN11"},
    {"formula": "Ref($open, 10)/$close", "name": "qlib360_OPEN10"},
    {"formula": "Ref($open, 9)/$close", "name": "qlib360_OPEN9"},
    {"formula": "Ref($open, 8)/$close", "name": "qlib360_OPEN8"},
    {"formula": "Ref($open, 7)/$close", "name": "qlib360_OPEN7"},
    {"formula": "Ref($open, 6)/$close", "name": "qlib360_OPEN6"},
    {"formula": "Ref($open, 5)/$close", "name": "qlib360_OPEN5"},
    {"formula": "Ref($open, 4)/$close", "name": "qlib360_OPEN4"},
    {"formula": "Ref($open, 3)/$close", "name": "qlib360_OPEN3"},
    {"formula": "Ref($open, 2)/$close", "name": "qlib360_OPEN2"},
    {"formula": "Ref($open, 1)/$close", "name": "qlib360_OPEN1"},
    {"formula": "$open/$close", "name": "qlib360_OPEN0"},
    {"formula": "Ref($high, 59)/$close", "name": "qlib360_HIGH59"},
    {"formula": "Ref($high, 58)/$close", "name": "qlib360_HIGH58"},
    {"formula": "Ref($high, 57)/$close", "name": "qlib360_HIGH57"},
    {"formula": "Ref($high, 56)/$close", "name": "qlib360_HIGH56"},
    {"formula": "Ref($high, 55)/$close", "name": "qlib360_HIGH55"},
    {"formula": "Ref($high, 54)/$close", "name": "qlib360_HIGH54"},
    {"formula": "Ref($high, 53)/$close", "name": "qlib360_HIGH53"},
    {"formula": "Ref($high, 52)/$close", "name": "qlib360_HIGH52"},
    {"formula": "Ref($high, 51)/$close", "name": "qlib360_HIGH51"},
    {"formula": "Ref($high, 50)/$close", "name": "qlib360_HIGH50"},
    {"formula": "Ref($high, 49)/$close", "name": "qlib360_HIGH49"},
    {"formula": "Ref($high, 48)/$close", "name": "qlib360_HIGH48"},
    {"formula": "Ref($high, 47)/$close", "name": "qlib360_HIGH47"},
    {"formula": "Ref($high, 46)/$close", "name": "qlib360_HIGH46"},
    {"formula": "Ref($high, 45)/$close", "name": "qlib360_HIGH45"},
    {"formula": "Ref($high, 44)/$close", "name": "qlib360_HIGH44"},
    {"formula": "Ref($high, 43)/$close", "name": "qlib360_HIGH43"},
    {"formula": "Ref($high, 42)/$close", "name": "qlib360_HIGH42"},
    {"formula": "Ref($high, 41)/$close", "name": "qlib360_HIGH41"},
    {"formula": "Ref($high, 40)/$close", "name": "qlib360_HIGH40"},
    {"formula": "Ref($high, 39)/$close", "name": "qlib360_HIGH39"},
    {"formula": "Ref($high, 38)/$close", "name": "qlib360_HIGH38"},
    {"formula": "Ref($high, 37)/$close", "name": "qlib360_HIGH37"},
    {"formula": "Ref($high, 36)/$close", "name": "qlib360_HIGH36"},
    {"formula": "Ref($high, 35)/$close", "name": "qlib360_HIGH35"},
    {"formula": "Ref($high, 34)/$close", "name": "qlib360_HIGH34"},
    {"formula": "Ref($high, 33)/$close", "name": "qlib360_HIGH33"},
    {"formula": "Ref($high, 32)/$close", "name": "qlib360_HIGH32"},
    {"formula": "Ref($high, 31)/$close", "name": "qlib360_HIGH31"},
    {"formula": "Ref($high, 30)/$close", "name": "qlib360_HIGH30"},
    {"formula": "Ref($high, 29)/$close", "name": "qlib360_HIGH29"},
    {"formula": "Ref($high, 28)/$close", "name": "qlib360_HIGH28"},
    {"formula": "Ref($high, 27)/$close", "name": "qlib360_HIGH27"},
    {"formula": "Ref($high, 26)/$close", "name": "qlib360_HIGH26"},
    {"formula": "Ref($high, 25)/$close", "name": "qlib360_HIGH25"},
    {"formula": "Ref($high, 24)/$close", "name": "qlib360_HIGH24"},
    {"formula": "Ref($high, 23)/$close", "name": "qlib360_HIGH23"},
    {"formula": "Ref($high, 22)/$close", "name": "qlib360_HIGH22"},
    {"formula": "Ref($high, 21)/$close", "name": "qlib360_HIGH21"},
    {"formula": "Ref($high, 20)/$close", "name": "qlib360_HIGH20"},
    {"formula": "Ref($high, 19)/$close", "name": "qlib360_HIGH19"},
    {"formula": "Ref($high, 18)/$close", "name": "qlib360_HIGH18"},
    {"formula": "Ref($high, 17)/$close", "name": "qlib360_HIGH17"},
    {"formula": "Ref($high, 16)/$close", "name": "qlib360_HIGH16"},
    {"formula": "Ref($high, 15)/$close", "name": "qlib360_HIGH15"},
    {"formula": "Ref($high, 14)/$close", "name": "qlib360_HIGH14"},
    {"formula": "Ref($high, 13)/$close", "name": "qlib360_HIGH13"},
    {"formula": "Ref($high, 12)/$close", "name": "qlib360_HIGH12"},
    {"formula": "Ref($high, 11)/$close", "name": "qlib360_HIGH11"},
    {"formula": "Ref($high, 10)/$close", "name": "qlib360_HIGH10"},
    {"formula": "Ref($high, 9)/$close", "name": "qlib360_HIGH9"},
    {"formula": "Ref($high, 8)/$close", "name": "qlib360_HIGH8"},
    {"formula": "Ref($high, 7)/$close", "name": "qlib360_HIGH7"},
    {"formula": "Ref($high, 6)/$close", "name": "qlib360_HIGH6"},
    {"formula": "Ref($high, 5)/$close", "name": "qlib360_HIGH5"},
    {"formula": "Ref($high, 4)/$close", "name": "qlib360_HIGH4"},
    {"formula": "Ref($high, 3)/$close", "name": "qlib360_HIGH3"},
    {"formula": "Ref($high, 2)/$close", "name": "qlib360_HIGH2"},
    {"formula": "Ref($high, 1)/$close", "name": "qlib360_HIGH1"},
    {"formula": "$high/$close", "name": "qlib360_HIGH0"},
    {"formula": "Ref($low, 59)/$close", "name": "qlib360_LOW59"},
    {"formula": "Ref($low, 58)/$close", "name": "qlib360_LOW58"},
    {"formula": "Ref($low, 57)/$close", "name": "qlib360_LOW57"},
    {"formula": "Ref($low, 56)/$close", "name": "qlib360_LOW56"},
    {"formula": "Ref($low, 55)/$close", "name": "qlib360_LOW55"},
    {"formula": "Ref($low, 54)/$close", "name": "qlib360_LOW54"},
    {"formula": "Ref($low, 53)/$close", "name": "qlib360_LOW53"},
    {"formula": "Ref($low, 52)/$close", "name": "qlib360_LOW52"},
    {"formula": "Ref($low, 51)/$close", "name": "qlib360_LOW51"},
    {"formula": "Ref($low, 50)/$close", "name": "qlib360_LOW50"},
    {"formula": "Ref($low, 49)/$close", "name": "qlib360_LOW49"},
    {"formula": "Ref($low, 48)/$close", "name": "qlib360_LOW48"},
    {"formula": "Ref($low, 47)/$close", "name": "qlib360_LOW47"},
    {"formula": "Ref($low, 46)/$close", "name": "qlib360_LOW46"},
    {"formula": "Ref($low, 45)/$close", "name": "qlib360_LOW45"},
    {"formula": "Ref($low, 44)/$close", "name": "qlib360_LOW44"},
    {"formula": "Ref($low, 43)/$close", "name": "qlib360_LOW43"},
    {"formula": "Ref($low, 42)/$close", "name": "qlib360_LOW42"},
    {"formula": "Ref($low, 41)/$close", "name": "qlib360_LOW41"},
    {"formula": "Ref($low, 40)/$close", "name": "qlib360_LOW40"},
    {"formula": "Ref($low, 39)/$close", "name": "qlib360_LOW39"},
    {"formula": "Ref($low, 38)/$close", "name": "qlib360_LOW38"},
    {"formula": "Ref($low, 37)/$close", "name": "qlib360_LOW37"},
    {"formula": "Ref($low, 36)/$close", "name": "qlib360_LOW36"},
    {"formula": "Ref($low, 35)/$close", "name": "qlib360_LOW35"},
    {"formula": "Ref($low, 34)/$close", "name": "qlib360_LOW34"},
    {"formula": "Ref($low, 33)/$close", "name": "qlib360_LOW33"},
    {"formula": "Ref($low, 32)/$close", "name": "qlib360_LOW32"},
    {"formula": "Ref($low, 31)/$close", "name": "qlib360_LOW31"},
    {"formula": "Ref($low, 30)/$close", "name": "qlib360_LOW30"},
    {"formula": "Ref($low, 29)/$close", "name": "qlib360_LOW29"},
    {"formula": "Ref($low, 28)/$close", "name": "qlib360_LOW28"},
    {"formula": "Ref($low, 27)/$close", "name": "qlib360_LOW27"},
    {"formula": "Ref($low, 26)/$close", "name": "qlib360_LOW26"},
    {"formula": "Ref($low, 25)/$close", "name": "qlib360_LOW25"},
    {"formula": "Ref($low, 24)/$close", "name": "qlib360_LOW24"},
    {"formula": "Ref($low, 23)/$close", "name": "qlib360_LOW23"},
    {"formula": "Ref($low, 22)/$close", "name": "qlib360_LOW22"},
    {"formula": "Ref($low, 21)/$close", "name": "qlib360_LOW21"},
    {"formula": "Ref($low, 20)/$close", "name": "qlib360_LOW20"},
    {"formula": "Ref($low, 19)/$close", "name": "qlib360_LOW19"},
    {"formula": "Ref($low, 18)/$close", "name": "qlib360_LOW18"},
    {"formula": "Ref($low, 17)/$close", "name": "qlib360_LOW17"},
    {"formula": "Ref($low, 16)/$close", "name": "qlib360_LOW16"},
    {"formula": "Ref($low, 15)/$close", "name": "qlib360_LOW15"},
    {"formula": "Ref($low, 14)/$close", "name": "qlib360_LOW14"},
    {"formula": "Ref($low, 13)/$close", "name": "qlib360_LOW13"},
    {"formula": "Ref($low, 12)/$close", "name": "qlib360_LOW12"},
    {"formula": "Ref($low, 11)/$close", "name": "qlib360_LOW11"},
    {"formula": "Ref($low, 10)/$close", "name": "qlib360_LOW10"},
    {"formula": "Ref($low, 9)/$close", "name": "qlib360_LOW9"},
    {"formula": "Ref($low, 8)/$close", "name": "qlib360_LOW8"},
    {"formula": "Ref($low, 7)/$close", "name": "qlib360_LOW7"},
    {"formula": "Ref($low, 6)/$close", "name": "qlib360_LOW6"},
    {"formula": "Ref($low, 5)/$close", "name": "qlib360_LOW5"},
    {"formula": "Ref($low, 4)/$close", "name": "qlib360_LOW4"},
    {"formula": "Ref($low, 3)/$close", "name": "qlib360_LOW3"},
    {"formula": "Ref($low, 2)/$close", "name": "qlib360_LOW2"},
    {"formula": "Ref($low, 1)/$close", "name": "qlib360_LOW1"},
    {"formula": "$low/$close", "name": "qlib360_LOW0"},
    {"formula": "Ref($vwap, 59)/$close", "name": "qlib360_VWAP59"},
    {"formula": "Ref($vwap, 58)/$close", "name": "qlib360_VWAP58"},
    {"formula": "Ref($vwap, 57)/$close", "name": "qlib360_VWAP57"},
    {"formula": "Ref($vwap, 56)/$close", "name": "qlib360_VWAP56"},
    {"formula": "Ref($vwap, 55)/$close", "name": "qlib360_VWAP55"},
    {"formula": "Ref($vwap, 54)/$close", "name": "qlib360_VWAP54"},
    {"formula": "Ref($vwap, 53)/$close", "name": "qlib360_VWAP53"},
    {"formula": "Ref($vwap, 52)/$close", "name": "qlib360_VWAP52"},
    {"formula": "Ref($vwap, 51)/$close", "name": "qlib360_VWAP51"},
    {"formula": "Ref($vwap, 50)/$close", "name": "qlib360_VWAP50"},
    {"formula": "Ref($vwap, 49)/$close", "name": "qlib360_VWAP49"},
    {"formula": "Ref($vwap, 48)/$close", "name": "qlib360_VWAP48"},
    {"formula": "Ref($vwap, 47)/$close", "name": "qlib360_VWAP47"},
    {"formula": "Ref($vwap, 46)/$close", "name": "qlib360_VWAP46"},
    {"formula": "Ref($vwap, 45)/$close", "name": "qlib360_VWAP45"},
    {"formula": "Ref($vwap, 44)/$close", "name": "qlib360_VWAP44"},
    {"formula": "Ref($vwap, 43)/$close", "name": "qlib360_VWAP43"},
    {"formula": "Ref($vwap, 42)/$close", "name": "qlib360_VWAP42"},
    {"formula": "Ref($vwap, 41)/$close", "name": "qlib360_VWAP41"},
    {"formula": "Ref($vwap, 40)/$close", "name": "qlib360_VWAP40"},
    {"formula": "Ref($vwap, 39)/$close", "name": "qlib360_VWAP39"},
    {"formula": "Ref($vwap, 38)/$close", "name": "qlib360_VWAP38"},
    {"formula": "Ref($vwap, 37)/$close", "name": "qlib360_VWAP37"},
    {"formula": "Ref($vwap, 36)/$close", "name": "qlib360_VWAP36"},
    {"formula": "Ref($vwap, 35)/$close", "name": "qlib360_VWAP35"},
    {"formula": "Ref($vwap, 34)/$close", "name": "qlib360_VWAP34"},
    {"formula": "Ref($vwap, 33)/$close", "name": "qlib360_VWAP33"},
    {"formula": "Ref($vwap, 32)/$close", "name": "qlib360_VWAP32"},
    {"formula": "Ref($vwap, 31)/$close", "name": "qlib360_VWAP31"},
    {"formula": "Ref($vwap, 30)/$close", "name": "qlib360_VWAP30"},
    {"formula": "Ref($vwap, 29)/$close", "name": "qlib360_VWAP29"},
    {"formula": "Ref($vwap, 28)/$close", "name": "qlib360_VWAP28"},
    {"formula": "Ref($vwap, 27)/$close", "name": "qlib360_VWAP27"},
    {"formula": "Ref($vwap, 26)/$close", "name": "qlib360_VWAP26"},
    {"formula": "Ref($vwap, 25)/$close", "name": "qlib360_VWAP25"},
    {"formula": "Ref($vwap, 24)/$close", "name": "qlib360_VWAP24"},
    {"formula": "Ref($vwap, 23)/$close", "name": "qlib360_VWAP23"},
    {"formula": "Ref($vwap, 22)/$close", "name": "qlib360_VWAP22"},
    {"formula": "Ref($vwap, 21)/$close", "name": "qlib360_VWAP21"},
    {"formula": "Ref($vwap, 20)/$close", "name": "qlib360_VWAP20"},
    {"formula": "Ref($vwap, 19)/$close", "name": "qlib360_VWAP19"},
    {"formula": "Ref($vwap, 18)/$close", "name": "qlib360_VWAP18"},
    {"formula": "Ref($vwap, 17)/$close", "name": "qlib360_VWAP17"},
    {"formula": "Ref($vwap, 16)/$close", "name": "qlib360_VWAP16"},
    {"formula": "Ref($vwap, 15)/$close", "name": "qlib360_VWAP15"},
    {"formula": "Ref($vwap, 14)/$close", "name": "qlib360_VWAP14"},
    {"formula": "Ref($vwap, 13)/$close", "name": "qlib360_VWAP13"},
    {"formula": "Ref($vwap, 12)/$close", "name": "qlib360_VWAP12"},
    {"formula": "Ref($vwap, 11)/$close", "name": "qlib360_VWAP11"},
    {"formula": "Ref($vwap, 10)/$close", "name": "qlib360_VWAP10"},
    {"formula": "Ref($vwap, 9)/$close", "name": "qlib360_VWAP9"},
    {"formula": "Ref($vwap, 8)/$close", "name": "qlib360_VWAP8"},
    {"formula": "Ref($vwap, 7)/$close", "name": "qlib360_VWAP7"},
    {"formula": "Ref($vwap, 6)/$close", "name": "qlib360_VWAP6"},
    {"formula": "Ref($vwap, 5)/$close", "name": "qlib360_VWAP5"},
    {"formula": "Ref($vwap, 4)/$close", "name": "qlib360_VWAP4"},
    {"formula": "Ref($vwap, 3)/$close", "name": "qlib360_VWAP3"},
    {"formula": "Ref($vwap, 2)/$close", "name": "qlib360_VWAP2"},
    {"formula": "Ref($vwap, 1)/$close", "name": "qlib360_VWAP1"},
    {"formula": "$vwap/$close", "name": "qlib360_VWAP0"},
    {"formula": "Ref($volume, 59)/($volume+1e-12)", "name": "qlib360_VOLUME59"},
    {"formula": "Ref($volume, 58)/($volume+1e-12)", "name": "qlib360_VOLUME58"},
    {"formula": "Ref($volume, 57)/($volume+1e-12)", "name": "qlib360_VOLUME57"},
    {"formula": "Ref($volume, 56)/($volume+1e-12)", "name": "qlib360_VOLUME56"},
    {"formula": "Ref($volume, 55)/($volume+1e-12)", "name": "qlib360_VOLUME55"},
    {"formula": "Ref($volume, 54)/($volume+1e-12)", "name": "qlib360_VOLUME54"},
    {"formula": "Ref($volume, 53)/($volume+1e-12)", "name": "qlib360_VOLUME53"},
    {"formula": "Ref($volume, 52)/($volume+1e-12)", "name": "qlib360_VOLUME52"},
    {"formula": "Ref($volume, 51)/($volume+1e-12)", "name": "qlib360_VOLUME51"},
    {"formula": "Ref($volume, 50)/($volume+1e-12)", "name": "qlib360_VOLUME50"},
    {"formula": "Ref($volume, 49)/($volume+1e-12)", "name": "qlib360_VOLUME49"},
    {"formula": "Ref($volume, 48)/($volume+1e-12)", "name": "qlib360_VOLUME48"},
    {"formula": "Ref($volume, 47)/($volume+1e-12)", "name": "qlib360_VOLUME47"},
    {"formula": "Ref($volume, 46)/($volume+1e-12)", "name": "qlib360_VOLUME46"},
    {"formula": "Ref($volume, 45)/($volume+1e-12)", "name": "qlib360_VOLUME45"},
    {"formula": "Ref($volume, 44)/($volume+1e-12)", "name": "qlib360_VOLUME44"},
    {"formula": "Ref($volume, 43)/($volume+1e-12)", "name": "qlib360_VOLUME43"},
    {"formula": "Ref($volume, 42)/($volume+1e-12)", "name": "qlib360_VOLUME42"},
    {"formula": "Ref($volume, 41)/($volume+1e-12)", "name": "qlib360_VOLUME41"},
    {"formula": "Ref($volume,40)/($volume+1e-12)", "name": "qlib360_VOLUME40"},
    {"formula": "Ref($volume, 39)/($volume+1e-12)", "name": "qlib360_VOLUME39"},
    {"formula": "Ref($volume, 38)/($volume+1e-12)", "name": "qlib360_VOLUME38"},
    {"formula": "Ref($volume, 37)/($volume+1e-12)", "name": "qlib360_VOLUME37"},
    {"formula": "Ref($volume, 36)/($volume+1e-12)", "name": "qlib360_VOLUME36"},
    {"formula": "Ref($volume, 35)/($volume+1e-12)", "name": "qlib360_VOLUME35"},
    {"formula": "Ref($volume, 34)/($volume+1e-12)", "name": "qlib360_VOLUME34"},
    {"formula": "Ref($volume, 33)/($volume+1e-12)", "name": "qlib360_VOLUME33"},
    {"formula": "Ref($volume, 32)/($volume+1e-12)", "name": "qlib360_VOLUME32"},
    {"formula": "Ref($volume, 31)/($volume+1e-12)", "name": "qlib360_VOLUME31"},
    {"formula": "Ref($volume, 30)/($volume+1e-12)", "name": "qlib360_VOLUME30"},
    {"formula": "Ref($volume, 29)/($volume+1e-12)", "name": "qlib360_VOLUME29"},
    {"formula": "Ref($volume, 28)/($volume+1e-12)", "name": "qlib360_VOLUME28"},
    {"formula": "Ref($volume, 27)/($volume+1e-12)", "name": "qlib360_VOLUME27"},
    {"formula": "Ref($volume, 26)/($volume+1e-12)", "name": "qlib360_VOLUME26"},
    {"formula": "Ref($volume, 25)/($volume+1e-12)", "name": "qlib360_VOLUME25"},
    {"formula": "Ref($volume, 24)/($volume+1e-12)", "name": "qlib360_VOLUME24"},
    {"formula": "Ref($volume, 23)/($volume+1e-12)", "name": "qlib360_VOLUME23"},
    {"formula": "Ref($volume, 22)/($volume+1e-12)", "name": "qlib360_VOLUME22"},
    {"formula": "Ref($volume, 21)/($volume+1e-12)", "name": "qlib360_VOLUME21"},
    {"formula": "Ref($volume, 20)/($volume+1e-12)", "name": "qlib360_VOLUME20"},
    {"formula": "Ref($volume, 19)/($volume+1e-12)", "name": "qlib360_VOLUME19"},
    {"formula": "Ref($volume, 18)/($volume+1e-12)", "name": "qlib360_VOLUME18"},
    {"formula": "Ref($volume, 17)/($volume+1e-12)", "name": "qlib360_VOLUME17"},
    {"formula": "Ref($volume, 16)/($volume+1e-12)", "name": "qlib360_VOLUME16"},
    {"formula": "Ref($volume, 15)/($volume+1e-12)", "name": "qlib360_VOLUME15"},
    {"formula": "Ref($volume, 14)/($volume+1e-12)", "name": "qlib360_VOLUME14"},
    {"formula": "Ref($volume, 13)/($volume+1e-12)", "name": "qlib360_VOLUME13"},
    {"formula": "Ref($volume, 12)/($volume+1e-12)", "name": "qlib360_VOLUME12"},
    {"formula": "Ref($volume, 11)/($volume+1e-12)", "name": "qlib360_VOLUME11"},
    {"formula": "Ref($volume, 10)/($volume+1e-12)", "name": "qlib360_VOLUME10"},
    {"formula": "Ref($volume, 9)/($volume+1e-12)", "name": "qlib360_VOLUME9"},
    {"formula": "Ref($volume, 8)/($volume+1e-12)", "name": "qlib360_VOLUME8"},
    {"formula": "Ref($volume, 7)/($volume+1e-12)", "name": "qlib360_VOLUME7"},
    {"formula": "Ref($volume, 6)/($volume+1e-12)", "name": "qlib360_VOLUME6"},
    {"formula": "Ref($volume, 5)/($volume+1e-12)", "name": "qlib360_VOLUME5"},
    {"formula": "Ref($volume, 4)/($volume+1e-12)", "name": "qlib360_VOLUME4"},
    {"formula": "Ref($volume, 3)/($volume+1e-12)", "name": "qlib360_VOLUME3"},
    {"formula": "Ref($volume, 2)/($volume+1e-12)", "name": "qlib360_VOLUME2"},
    {"formula": "Ref($volume, 1)/($volume+1e-12)", "name": "qlib360_VOLUME1"},
    {"formula": "$volume/($volume+1e-12)", "name": "qlib360_VOLUME0"},
]
qlib_alpha158 = [
    {"formula": "($close-$open)/$open", "name": "qlib158_KMID"},
    {"formula": "($high-$low)/$open", "name": "qlib158_KLEN"},
    {"formula": "($close-$open)/($high-$low+1e-12)", "name": "qlib158_KMID2"},
    {"formula": "($high-Greater($open, $close))/$open", "name": "qlib158_KUP"},
    {
        "formula": "($high-Greater($open, $close))/($high-$low+1e-12)",
        "name": "qlib158_KUP2",
    },
    {"formula": "(Less($open, $close)-$low)/$open", "name": "qlib158_KLOW"},
    {
        "formula": "(Less($open, $close)-$low)/($high-$low+1e-12)",
        "name": "qlib158_KLOW2",
    },
    {"formula": "(2*$close-$high-$low)/$open", "name": "qlib158_KSFT"},
    {"formula": "(2*$close-$high-$low)/($high-$low+1e-12)", "name": "qlib158_KSFT2"},
    {"formula": "$open/$close", "name": "qlib158_OPEN0"},
    {"formula": "$high/$close", "name": "qlib158_HIGH0"},
    {"formula": "$low/$close", "name": "qlib158_LOW0"},
    {"formula": "$vwap/$close", "name": "qlib158_VWAP0"},
    {"formula": "Ref($close, 5)/$close", "name": "qlib158_ROC5"},
    {"formula": "Ref($close, 10)/$close", "name": "qlib158_ROC10"},
    {"formula": "Ref($close, 20)/$close", "name": "qlib158_ROC20"},
    {"formula": "Ref($close, 30)/$close", "name": "qlib158_ROC30"},
    {"formula": "Ref($close, 60)/$close", "name": "qlib158_ROC60"},
    {"formula": "Mean($close, 5)/$close", "name": "qlib158_MA5"},
    {"formula": "Mean($close, 10)/$close", "name": "qlib158_MA10"},
    {"formula": "Mean($close, 20)/$close", "name": "qlib158_MA20"},
    {"formula": "Mean($close, 30)/$close", "name": "qlib158_MA30"},
    {"formula": "Mean($close, 60)/$close", "name": "qlib158_MA60"},
    {"formula": "Std($close, 5)/$close", "name": "qlib158_STD5"},
    {"formula": "Std($close, 10)/$close", "name": "qlib158_STD10"},
    {"formula": "Std($close, 20)/$close", "name": "qlib158_STD20"},
    {"formula": "Std($close, 30)/$close", "name": "qlib158_STD30"},
    {"formula": "Std($close, 60)/$close", "name": "qlib158_STD60"},
    {"formula": "Slope($close, 5)/$close", "name": "qlib158_BETA5"},
    {"formula": "Slope($close, 10)/$close", "name": "qlib158_BETA10"},
    {"formula": "Slope($close, 20)/$close", "name": "qlib158_BETA20"},
    {"formula": "Slope($close, 30)/$close", "name": "qlib158_BETA30"},
    {"formula": "Slope($close, 60)/$close", "name": "qlib158_BETA60"},
    {"formula": "Rsquare($close, 5)", "name": "qlib158_RSQR5"},
    {"formula": "Rsquare($close, 10)", "name": "qlib158_RSQR10"},
    {"formula": "Rsquare($close, 20)", "name": "qlib158_RSQR20"},
    {"formula": "Rsquare($close, 30)", "name": "qlib158_RSQR30"},
    {"formula": "Rsquare($close, 60)", "name": "qlib158_RSQR60"},
    {"formula": "Resi($close, 5)/$close", "name": "qlib158_RESI5"},
    {"formula": "Resi($close, 10)/$close", "name": "qlib158_RESI10"},
    {"formula": "Resi($close, 20)/$close", "name": "qlib158_RESI20"},
    {"formula": "Resi($close, 30)/$close", "name": "qlib158_RESI30"},
    {"formula": "Resi($close, 60)/$close", "name": "qlib158_RESI60"},
    {"formula": "Max($high, 5)/$close", "name": "qlib158_MAX5"},
    {"formula": "Max($high, 10)/$close", "name": "qlib158_MAX10"},
    {"formula": "Max($high, 20)/$close", "name": "qlib158_MAX20"},
    {"formula": "Max($high, 30)/$close", "name": "qlib158_MAX30"},
    {"formula": "Max($high, 60)/$close", "name": "qlib158_MAX60"},
    {"formula": "Min($low, 5)/$close", "name": "qlib158_MIN5"},
    {"formula": "Min($low, 10)/$close", "name": "qlib158_MIN10"},
    {"formula": "Min($low, 20)/$close", "name": "qlib158_MIN20"},
    {"formula": "Min($low, 30)/$close", "name": "qlib158_MIN30"},
    {"formula": "Min($low, 60)/$close", "name": "qlib158_MIN60"},
    {"formula": "Quantile($close, 5, 0.8)/$close", "name": "qlib158_QTLU5"},
    {"formula": "Quantile($close, 10, 0.8)/$close", "name": "qlib158_QTLU10"},
    {"formula": "Quantile($close, 20, 0.8)/$close", "name": "qlib158_QTLU20"},
    {"formula": "Quantile($close, 30, 0.8)/$close", "name": "qlib158_QTLU30"},
    {"formula": "Quantile($close, 60, 0.8)/$close", "name": "qlib158_QTLU60"},
    {"formula": "Quantile($close, 5,0.2)/$close", "name": "qlib158_QTLD5"},
    {"formula": "Quantile($close, 10, 0.2)/$close", "name": "qlib158_QTLD10"},
    {"formula": "Quantile($close, 20, 0.2)/$close", "name": "qlib158_QTLD20"},
    {"formula": "Quantile($close, 30, 0.2)/$close", "name": "qlib158_QTLD30"},
    {"formula": "Quantile($close, 60, 0.2)/$close", "name": "qlib158_QTLD60"},
    {"formula": "Rank($close, 5)", "name": "qlib158_RANK5"},
    {"formula": "Rank($close, 10)", "name": "qlib158_RANK10"},
    {"formula": "Rank($close, 20)", "name": "qlib158_RANK20"},
    {"formula": "Rank($close, 30)", "name": "qlib158_RANK30"},
    {"formula": "Rank($close, 60)", "name": "qlib158_RANK60"},
    {
        "formula": "($close-Min($low, 5))/(Max($high, 5)-Min($low, 5)+1e-12)",
        "name": "qlib158_RSV5",
    },
    {
        "formula": "($close-Min($low, 10))/(Max($high, 10)-Min($low, 10)+1e-12)",
        "name": "qlib158_RSV10",
    },
    {
        "formula": "($close-Min($low, 20))/(Max($high, 20)-Min($low, 20)+1e-12)",
        "name": "qlib158_RSV20",
    },
    {
        "formula": "($close-Min($low, 30))/(Max($high, 30)-Min($low, 30)+1e-12)",
        "name": "qlib158_RSV30",
    },
    {
        "formula": "($close-Min($low, 60))/(Max($high, 60)-Min($low, 60)+1e-12)",
        "name": "qlib158_RSV60",
    },
    {"formula": "IdxMax($high, 5)/5", "name": "qlib158_IMAX5"},
    {"formula": "IdxMax($high, 10)/10", "name": "qlib158_IMAX10"},
    {"formula": "IdxMax($high, 20)/20", "name": "qlib158_IMAX20"},
    {"formula": "IdxMax($high, 30)/30", "name": "qlib158_IMAX30"},
    {"formula": "IdxMax($high, 60)/60", "name": "qlib158_IMAX60"},
    {"formula": "IdxMin($low, 5)/5", "name": "qlib158_IMIN5"},
    {"formula": "IdxMin($low, 10)/10", "name": "qlib158_IMIN10"},
    {"formula": "IdxMin($low, 20)/20", "name": "qlib158_IMIN20"},
    {"formula": "IdxMin($low, 30)/30", "name": "qlib158_IMIN30"},
    {"formula": "IdxMin($low, 60)/60", "name": "qlib158_IMIN60"},
    {"formula": "(IdxMax($high,5)-IdxMin($low, 5))/5", "name": "qlib158_IMXD5"},
    {"formula": "(IdxMax($high, 10)-IdxMin($low, 10))/10", "name": "qlib158_IMXD10"},
    {"formula": "(IdxMax($high, 20)-IdxMin($low, 20))/20", "name": "qlib158_IMXD20"},
    {"formula": "(IdxMax($high, 30)-IdxMin($low, 30))/30", "name": "qlib158_IMXD30"},
    {"formula": "(IdxMax($high, 60)-IdxMin($low, 60))/60", "name": "qlib158_IMXD60"},
    {"formula": "Corr($close, Log($volume+1), 5)", "name": "qlib158_CORR5"},
    {"formula": "Corr($close, Log($volume+1), 10)", "name": "qlib158_CORR10"},
    {"formula": "Corr($close, Log($volume+1), 20)", "name": "qlib158_CORR20"},
    {"formula": "Corr($close, Log($volume+1), 30)", "name": "qlib158_CORR30"},
    {"formula": "Corr($close, Log($volume+1), 60)", "name": "qlib158_CORR60"},
    {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 5)",
        "name": "qlib158_CORD5",
    },
    {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 10)",
        "name": "qlib158_CORD10",
    },
    {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 20)",
        "name": "qlib158_CORD20",
    },
    {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 30)",
        "name": "qlib158_CORD30",
    },
    {
        "formula": "Corr($close/Ref($close,1), Log($volume/Ref($volume, 1)+1), 60)",
        "name": "qlib158_CORD60",
    },
    {"formula": "Mean($close>Ref($close, 1), 5)", "name": "qlib158_CNTP5"},
    {"formula": "Mean($close>Ref($close, 1), 10)", "name": "qlib158_CNTP10"},
    {"formula": "Mean($close>Ref($close, 1), 20)", "name": "qlib158_CNTP20"},
    {"formula": "Mean($close>Ref($close, 1), 30)", "name": "qlib158_CNTP30"},
    {"formula": "Mean($close>Ref($close, 1), 60)", "name": "qlib158_CNTP60"},
    {"formula": "Mean($close<Ref($close, 1), 5)", "name": "qlib158_CNTN5"},
    {"formula": "Mean($close<Ref($close, 1), 10)", "name": "qlib158_CNTN10"},
    {"formula": "Mean($close<Ref($close, 1), 20)", "name": "qlib158_CNTN20"},
    {"formula": "Mean($close<Ref($close, 1), 30)", "name": "qlib158_CNTN30"},
    {"formula": "Mean($close<Ref($close, 1), 60)", "name": "qlib158_CNTN60"},
    {
        "formula": "Mean($close>Ref($close, 1), 5)-Mean($close<Ref($close, 1), 5)",
        "name": "qlib158_CNTD5",
    },
    {
        "formula": "Mean($close>Ref($close, 1), 10)-Mean($close<Ref($close, 1), 10)",
        "name": "qlib158_CNTD10",
    },
    {
        "formula": "Mean($close>Ref($close, 1), 20)-Mean($close<Ref($close, 1), 20)",
        "name": "qlib158_CNTD20",
    },
    {
        "formula": "Mean($close>Ref($close, 1), 30)-Mean($close<Ref($close, 1), 30)",
        "name": "qlib158_CNTD30",
    },
    {
        "formula": "Mean($close>Ref($close, 1), 60)-Mean($close<Ref($close, 1), 60)",
        "name": "qlib158_CNTD60",
    },
    {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 5)/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "name": "qlib158_SUMP5",
    },
    {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 10)/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "name": "qlib158_SUMP10",
    },
    {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 20)/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "name": "qlib158_SUMP20",
    },
    {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 30)/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "name": "qlib158_SUMP30",
    },
    {
        "formula": "Sum(Greater($close-Ref($close, 1), 0), 60)/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "name": "qlib158_SUMP60",
    },
    {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 5)/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "name": "qlib158_SUMN5",
    },
    {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 10)/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "name": "qlib158_SUMN10",
    },
    {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 20)/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "name": "qlib158_SUMN20",
    },
    {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 30)/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "name": "qlib158_SUMN30",
    },
    {
        "formula": "Sum(Greater(Ref($close, 1)-$close, 0), 60)/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "name": "qlib158_SUMN60",
    },
    {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 5)-Sum(Greater(Ref($close, 1)-$close, 0), 5))/(Sum(Abs($close-Ref($close, 1)), 5)+1e-12)",
        "name": "qlib158_SUMD5",
    },
    {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 10)-Sum(Greater(Ref($close, 1)-$close, 0), 10))/(Sum(Abs($close-Ref($close, 1)), 10)+1e-12)",
        "name": "qlib158_SUMD10",
    },
    {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 20)-Sum(Greater(Ref($close, 1)-$close, 0), 20))/(Sum(Abs($close-Ref($close, 1)), 20)+1e-12)",
        "name": "qlib158_SUMD20",
    },
    {
        "formula": "(Sum(Greater($close-Ref($close,1), 0), 30)-Sum(Greater(Ref($close, 1)-$close, 0), 30))/(Sum(Abs($close-Ref($close, 1)), 30)+1e-12)",
        "name": "qlib158_SUMD30",
    },
    {
        "formula": "(Sum(Greater($close-Ref($close, 1), 0), 60)-Sum(Greater(Ref($close, 1)-$close, 0), 60))/(Sum(Abs($close-Ref($close, 1)), 60)+1e-12)",
        "name": "qlib158_SUMD60",
    },
    {"formula": "Mean($volume, 5)/($volume+1e-12)", "name": "qlib158_VMA5"},
    {"formula": "Mean($volume, 10)/($volume+1e-12)", "name": "qlib158_VMA10"},
    {"formula": "Mean($volume, 20)/($volume+1e-12)", "name": "qlib158_VMA20"},
    {"formula": "Mean($volume, 30)/($volume+1e-12)", "name": "qlib158_VMA30"},
    {"formula": "Mean($volume, 60)/($volume+1e-12)", "name": "qlib158_VMA60"},
    {"formula": "Std($volume, 5)/($volume+1e-12)", "name": "qlib158_VSTD5"},
    {"formula": "Std($volume, 10)/($volume+1e-12)", "name": "qlib158_VSTD10"},
    {"formula": "Std($volume, 20)/($volume+1e-12)", "name": "qlib158_VSTD20"},
    {"formula": "Std($volume, 30)/($volume+1e-12)", "name": "qlib158_VSTD30"},
    {"formula": "Std($volume, 60)/($volume+1e-12)", "name": "qlib158_VSTD60"},
    {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 5)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 5)+1e-12)",
        "name": "qlib158_WVMA5",
    },
    {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 10)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 10)+1e-12)",
        "name": "qlib158_WVMA10",
    },
    {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 20)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 20)+1e-12)",
        "name": "qlib158_WVMA20",
    },
    {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 30)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 30)+1e-12)",
        "name": "qlib158_WVMA30",
    },
    {
        "formula": "Std(Abs($close/Ref($close, 1)-1)*$volume, 60)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 60)+1e-12)",
        "name": "qlib158_WVMA60",
    },
    {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 5)/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "name": "qlib158_VSUMP5",
    },
    {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 10)/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "name": "qlib158_VSUMP10",
    },
    {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 20)/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "name": "qlib158_VSUMP20",
    },
    {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 30)/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "name": "qlib158_VSUMP30",
    },
    {
        "formula": "Sum(Greater($volume-Ref($volume, 1), 0), 60)/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "name": "qlib158_VSUMP60",
    },
    {
        "formula": "Sum(Greater(Ref($volume,1)-$volume, 0), 5)/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "name": "qlib158_VSUMN5",
    },
    {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 10)/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "name": "qlib158_VSUMN10",
    },
    {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 20)/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "name": "qlib158_VSUMN20",
    },
    {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume,0), 30)/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "name": "qlib158_VSUMN30",
    },
    {
        "formula": "Sum(Greater(Ref($volume, 1)-$volume, 0), 60)/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "name": "qlib158_VSUMN60",
    },
    {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 5)-Sum(Greater(Ref($volume, 1)-$volume, 0), 5))/(Sum(Abs($volume-Ref($volume, 1)), 5)+1e-12)",
        "name": "qlib158_VSUMD5",
    },
    {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 10)-Sum(Greater(Ref($volume, 1)-$volume, 0), 10))/(Sum(Abs($volume-Ref($volume, 1)), 10)+1e-12)",
        "name": "qlib158_VSUMD10",
    },
    {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 20)-Sum(Greater(Ref($volume, 1)-$volume, 0), 20))/(Sum(Abs($volume-Ref($volume, 1)), 20)+1e-12)",
        "name": "qlib158_VSUMD20",
    },
    {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 30)-Sum(Greater(Ref($volume, 1)-$volume, 0), 30))/(Sum(Abs($volume-Ref($volume, 1)), 30)+1e-12)",
        "name": "qlib158_VSUMD30",
    },
    {
        "formula": "(Sum(Greater($volume-Ref($volume, 1), 0), 60)-Sum(Greater(Ref($volume, 1)-$volume, 0), 60))/(Sum(Abs($volume-Ref($volume, 1)), 60)+1e-12)",
        "name": "qlib158_VSUMD60",
    },
]
