"""
alpha_cfg = Alpha360DL.get_feature_config()

print(alpha_cfg)


cfg = (
    [
        "Delay($close, 59)/$close",
        "Delay($close, 58)/$close",
        "Delay($close, 57)/$close",
        "Delay($close, 56)/$close",
        "Delay($close, 55)/$close",
        "Delay($close, 54)/$close",
        "Delay($close, 53)/$close",
        "Delay($close, 52)/$close",
        "Delay($close, 51)/$close",
        "Delay($close, 50)/$close",
        "Delay($close, 49)/$close",
        "Delay($close, 48)/$close",
        "Delay($close, 47)/$close",
        "Delay($close, 46)/$close",
        "Delay($close, 45)/$close",
        "Delay($close, 44)/$close",
        "Delay($close, 43)/$close",
        "Delay($close, 42)/$close",
        "Delay($close, 41)/$close",
        "Delay($close, 40)/$close",
        "Delay($close, 39)/$close",
        "Delay($close, 38)/$close",
        "Delay($close, 37)/$close",
        "Delay($close, 36)/$close",
        "Delay($close, 35)/$close",
        "Delay($close, 34)/$close",
        "Delay($close, 33)/$close",
        "Delay($close, 32)/$close",
        "Delay($close, 31)/$close",
        "Delay($close, 30)/$close",
        "Delay($close, 29)/$close",
        "Delay($close, 28)/$close",
        "Delay($close, 27)/$close",
        "Delay($close, 26)/$close",
        "Delay($close, 25)/$close",
        "Delay($close, 24)/$close",
        "Delay($close, 23)/$close",
        "Delay($close, 22)/$close",
        "Delay($close, 21)/$close",
        "Delay($close, 20)/$close",
        "Delay($close, 19)/$close",
        "Delay($close, 18)/$close",
        "Delay($close, 17)/$close",
        "Delay($close, 16)/$close",
        "Delay($close, 15)/$close",
        "Delay($close, 14)/$close",
        "Delay($close, 13)/$close",
        "Delay($close, 12)/$close",
        "Delay($close, 11)/$close",
        "Delay($close, 10)/$close",
        "Delay($close, 9)/$close",
        "Delay($close, 8)/$close",
        "Delay($close, 7)/$close",
        "Delay($close, 6)/$close",
        "Delay($close, 5)/$close",
        "Delay($close, 4)/$close",
        "Delay($close, 3)/$close",
        "Delay($close, 2)/$close",
        "Delay($close, 1)/$close",
        "$close/$close",
        "Delay($open, 59)/$close",
        "Delay($open, 58)/$close",
        "Delay($open, 57)/$close",
        "Delay($open, 56)/$close",
        "Delay($open, 55)/$close",
        "Delay($open, 54)/$close",
        "Delay($open, 53)/$close",
        "Delay($open, 52)/$close",
        "Delay($open, 51)/$close",
        "Delay($open, 50)/$close",
        "Delay($open, 49)/$close",
        "Delay($open, 48)/$close",
        "Delay($open, 47)/$close",
        "Delay($open, 46)/$close",
        "Delay($open, 45)/$close",
        "Delay($open, 44)/$close",
        "Delay($open, 43)/$close",
        "Delay($open, 42)/$close",
        "Delay($open, 41)/$close",
        "Delay($open, 40)/$close",
        "Delay($open, 39)/$close",
        "Delay($open, 38)/$close",
        "Delay($open, 37)/$close",
        "Delay($open, 36)/$close",
        "Delay($open, 35)/$close",
        "Delay($open, 34)/$close",
        "Delay($open, 33)/$close",
        "Delay($open, 32)/$close",
        "Delay($open, 31)/$close",
        "Delay($open, 30)/$close",
        "Delay($open, 29)/$close",
        "Delay($open, 28)/$close",
        "Delay($open, 27)/$close",
        "Delay($open, 26)/$close",
        "Delay($open, 25)/$close",
        "Delay($open, 24)/$close",
        "Delay($open, 23)/$close",
        "Delay($open, 22)/$close",
        "Delay($open, 21)/$close",
        "Delay($open, 20)/$close",
        "Delay($open, 19)/$close",
        "Delay($open, 18)/$close",
        "Delay($open, 17)/$close",
        "Delay($open, 16)/$close",
        "Delay($open, 15)/$close",
        "Delay($open, 14)/$close",
        "Delay($open, 13)/$close",
        "Delay($open, 12)/$close",
        "Delay($open, 11)/$close",
        "Delay($open, 10)/$close",
        "Delay($open, 9)/$close",
        "Delay($open, 8)/$close",
        "Delay($open, 7)/$close",
        "Delay($open, 6)/$close",
        "Delay($open, 5)/$close",
        "Delay($open, 4)/$close",
        "Delay($open, 3)/$close",
        "Delay($open, 2)/$close",
        "Delay($open, 1)/$close",
        "$open/$close",
        "Delay($high, 59)/$close",
        "Delay($high, 58)/$close",
        "Delay($high, 57)/$close",
        "Delay($high, 56)/$close",
        "Delay($high, 55)/$close",
        "Delay($high, 54)/$close",
        "Delay($high, 53)/$close",
        "Delay($high, 52)/$close",
        "Delay($high, 51)/$close",
        "Delay($high, 50)/$close",
        "Delay($high, 49)/$close",
        "Delay($high, 48)/$close",
        "Delay($high, 47)/$close",
        "Delay($high, 46)/$close",
        "Delay($high, 45)/$close",
        "Delay($high, 44)/$close",
        "Delay($high, 43)/$close",
        "Delay($high, 42)/$close",
        "Delay($high, 41)/$close",
        "Delay($high, 40)/$close",
        "Delay($high, 39)/$close",
        "Delay($high, 38)/$close",
        "Delay($high, 37)/$close",
        "Delay($high, 36)/$close",
        "Delay($high, 35)/$close",
        "Delay($high, 34)/$close",
        "Delay($high, 33)/$close",
        "Delay($high, 32)/$close",
        "Delay($high, 31)/$close",
        "Delay($high, 30)/$close",
        "Delay($high, 29)/$close",
        "Delay($high, 28)/$close",
        "Delay($high, 27)/$close",
        "Delay($high, 26)/$close",
        "Delay($high, 25)/$close",
        "Delay($high, 24)/$close",
        "Delay($high, 23)/$close",
        "Delay($high, 22)/$close",
        "Delay($high, 21)/$close",
        "Delay($high, 20)/$close",
        "Delay($high, 19)/$close",
        "Delay($high, 18)/$close",
        "Delay($high, 17)/$close",
        "Delay($high, 16)/$close",
        "Delay($high, 15)/$close",
        "Delay($high, 14)/$close",
        "Delay($high, 13)/$close",
        "Delay($high, 12)/$close",
        "Delay($high, 11)/$close",
        "Delay($high, 10)/$close",
        "Delay($high, 9)/$close",
        "Delay($high, 8)/$close",
        "Delay($high, 7)/$close",
        "Delay($high, 6)/$close",
        "Delay($high, 5)/$close",
        "Delay($high, 4)/$close",
        "Delay($high, 3)/$close",
        "Delay($high, 2)/$close",
        "Delay($high, 1)/$close",
        "$high/$close",
        "Delay($low, 59)/$close",
        "Delay($low, 58)/$close",
        "Delay($low, 57)/$close",
        "Delay($low, 56)/$close",
        "Delay($low, 55)/$close",
        "Delay($low, 54)/$close",
        "Delay($low, 53)/$close",
        "Delay($low, 52)/$close",
        "Delay($low, 51)/$close",
        "Delay($low, 50)/$close",
        "Delay($low, 49)/$close",
        "Delay($low, 48)/$close",
        "Delay($low, 47)/$close",
        "Delay($low, 46)/$close",
        "Delay($low, 45)/$close",
        "Delay($low, 44)/$close",
        "Delay($low, 43)/$close",
        "Delay($low, 42)/$close",
        "Delay($low, 41)/$close",
        "Delay($low, 40)/$close",
        "Delay($low, 39)/$close",
        "Delay($low, 38)/$close",
        "Delay($low, 37)/$close",
        "Delay($low, 36)/$close",
        "Delay($low, 35)/$close",
        "Delay($low, 34)/$close",
        "Delay($low, 33)/$close",
        "Delay($low, 32)/$close",
        "Delay($low, 31)/$close",
        "Delay($low, 30)/$close",
        "Delay($low, 29)/$close",
        "Delay($low, 28)/$close",
        "Delay($low, 27)/$close",
        "Delay($low, 26)/$close",
        "Delay($low, 25)/$close",
        "Delay($low, 24)/$close",
        "Delay($low, 23)/$close",
        "Delay($low, 22)/$close",
        "Delay($low, 21)/$close",
        "Delay($low, 20)/$close",
        "Delay($low, 19)/$close",
        "Delay($low, 18)/$close",
        "Delay($low, 17)/$close",
        "Delay($low, 16)/$close",
        "Delay($low, 15)/$close",
        "Delay($low, 14)/$close",
        "Delay($low, 13)/$close",
        "Delay($low, 12)/$close",
        "Delay($low, 11)/$close",
        "Delay($low, 10)/$close",
        "Delay($low, 9)/$close",
        "Delay($low, 8)/$close",
        "Delay($low, 7)/$close",
        "Delay($low, 6)/$close",
        "Delay($low, 5)/$close",
        "Delay($low, 4)/$close",
        "Delay($low, 3)/$close",
        "Delay($low, 2)/$close",
        "Delay($low, 1)/$close",
        "$low/$close",
        "Delay($vwap, 59)/$close",
        "Delay($vwap, 58)/$close",
        "Delay($vwap, 57)/$close",
        "Delay($vwap, 56)/$close",
        "Delay($vwap, 55)/$close",
        "Delay($vwap, 54)/$close",
        "Delay($vwap, 53)/$close",
        "Delay($vwap, 52)/$close",
        "Delay($vwap, 51)/$close",
        "Delay($vwap, 50)/$close",
        "Delay($vwap, 49)/$close",
        "Delay($vwap, 48)/$close",
        "Delay($vwap, 47)/$close",
        "Delay($vwap, 46)/$close",
        "Delay($vwap, 45)/$close",
        "Delay($vwap, 44)/$close",
        "Delay($vwap, 43)/$close",
        "Delay($vwap, 42)/$close",
        "Delay($vwap, 41)/$close",
        "Delay($vwap, 40)/$close",
        "Delay($vwap, 39)/$close",
        "Delay($vwap, 38)/$close",
        "Delay($vwap, 37)/$close",
        "Delay($vwap, 36)/$close",
        "Delay($vwap, 35)/$close",
        "Delay($vwap, 34)/$close",
        "Delay($vwap, 33)/$close",
        "Delay($vwap, 32)/$close",
        "Delay($vwap, 31)/$close",
        "Delay($vwap, 30)/$close",
        "Delay($vwap, 29)/$close",
        "Delay($vwap, 28)/$close",
        "Delay($vwap, 27)/$close",
        "Delay($vwap, 26)/$close",
        "Delay($vwap, 25)/$close",
        "Delay($vwap, 24)/$close",
        "Delay($vwap, 23)/$close",
        "Delay($vwap, 22)/$close",
        "Delay($vwap, 21)/$close",
        "Delay($vwap, 20)/$close",
        "Delay($vwap, 19)/$close",
        "Delay($vwap, 18)/$close",
        "Delay($vwap, 17)/$close",
        "Delay($vwap, 16)/$close",
        "Delay($vwap, 15)/$close",
        "Delay($vwap, 14)/$close",
        "Delay($vwap, 13)/$close",
        "Delay($vwap, 12)/$close",
        "Delay($vwap, 11)/$close",
        "Delay($vwap, 10)/$close",
        "Delay($vwap, 9)/$close",
        "Delay($vwap, 8)/$close",
        "Delay($vwap, 7)/$close",
        "Delay($vwap, 6)/$close",
        "Delay($vwap, 5)/$close",
        "Delay($vwap, 4)/$close",
        "Delay($vwap, 3)/$close",
        "Delay($vwap, 2)/$close",
        "Delay($vwap, 1)/$close",
        "$vwap/$close",
        "Delay($volume, 59)/($volume+1e-12)",
        "Delay($volume, 58)/($volume+1e-12)",
        "Delay($volume, 57)/($volume+1e-12)",
        "Delay($volume, 56)/($volume+1e-12)",
        "Delay($volume, 55)/($volume+1e-12)",
        "Delay($volume, 54)/($volume+1e-12)",
        "Delay($volume, 53)/($volume+1e-12)",
        "Delay($volume, 52)/($volume+1e-12)",
        "Delay($volume, 51)/($volume+1e-12)",
        "Delay($volume, 50)/($volume+1e-12)",
        "Delay($volume, 49)/($volume+1e-12)",
        "Delay($volume, 48)/($volume+1e-12)",
        "Delay($volume, 47)/($volume+1e-12)",
        "Delay($volume, 46)/($volume+1e-12)",
        "Delay($volume, 45)/($volume+1e-12)",
        "Delay($volume, 44)/($volume+1e-12)",
        "Delay($volume, 43)/($volume+1e-12)",
        "Delay($volume, 42)/($volume+1e-12)",
        "Delay($volume, 41)/($volume+1e-12)",
        "Delay($volume, 40)/($volume+1e-12)",
        "Delay($volume, 39)/($volume+1e-12)",
        "Delay($volume, 38)/($volume+1e-12)",
        "Delay($volume, 37)/($volume+1e-12)",
        "Delay($volume, 36)/($volume+1e-12)",
        "Delay($volume, 35)/($volume+1e-12)",
        "Delay($volume, 34)/($volume+1e-12)",
        "Delay($volume, 33)/($volume+1e-12)",
        "Delay($volume, 32)/($volume+1e-12)",
        "Delay($volume, 31)/($volume+1e-12)",
        "Delay($volume, 30)/($volume+1e-12)",
        "Delay($volume, 29)/($volume+1e-12)",
        "Delay($volume, 28)/($volume+1e-12)",
        "Delay($volume, 27)/($volume+1e-12)",
        "Delay($volume, 26)/($volume+1e-12)",
        "Delay($volume, 25)/($volume+1e-12)",
        "Delay($volume, 24)/($volume+1e-12)",
        "Delay($volume, 23)/($volume+1e-12)",
        "Delay($volume, 22)/($volume+1e-12)",
        "Delay($volume, 21)/($volume+1e-12)",
        "Delay($volume, 20)/($volume+1e-12)",
        "Delay($volume, 19)/($volume+1e-12)",
        "Delay($volume, 18)/($volume+1e-12)",
        "Delay($volume, 17)/($volume+1e-12)",
        "Delay($volume, 16)/($volume+1e-12)",
        "Delay($volume, 15)/($volume+1e-12)",
        "Delay($volume, 14)/($volume+1e-12)",
        "Delay($volume, 13)/($volume+1e-12)",
        "Delay($volume, 12)/($volume+1e-12)",
        "Delay($volume, 11)/($volume+1e-12)",
        "Delay($volume, 10)/($volume+1e-12)",
        "Delay($volume, 9)/($volume+1e-12)",
        "Delay($volume, 8)/($volume+1e-12)",
        "Delay($volume, 7)/($volume+1e-12)",
        "Delay($volume, 6)/($volume+1e-12)",
        "Delay($volume, 5)/($volume+1e-12)",
        "Delay($volume, 4)/($volume+1e-12)",
        "Delay($volume, 3)/($volume+1e-12)",
        "Delay($volume, 2)/($volume+1e-12)",
        "Delay($volume, 1)/($volume+1e-12)",
        "$volume/($volume+1e-12)",
    ],
    [
        "CLOSE59",
        "CLOSE58",
        "CLOSE57",
        "CLOSE56",
        "CLOSE55",
        "CLOSE54",
        "CLOSE53",
        "CLOSE52",
        "CLOSE51",
        "CLOSE50",
        "CLOSE49",
        "CLOSE48",
        "CLOSE47",
        "CLOSE46",
        "CLOSE45",
        "CLOSE44",
        "CLOSE43",
        "CLOSE42",
        "CLOSE41",
        "CLOSE40",
        "CLOSE39",
        "CLOSE38",
        "CLOSE37",
        "CLOSE36",
        "CLOSE35",
        "CLOSE34",
        "CLOSE33",
        "CLOSE32",
        "CLOSE31",
        "CLOSE30",
        "CLOSE29",
        "CLOSE28",
        "CLOSE27",
        "CLOSE26",
        "CLOSE25",
        "CLOSE24",
        "CLOSE23",
        "CLOSE22",
        "CLOSE21",
        "CLOSE20",
        "CLOSE19",
        "CLOSE18",
        "CLOSE17",
        "CLOSE16",
        "CLOSE15",
        "CLOSE14",
        "CLOSE13",
        "CLOSE12",
        "CLOSE11",
        "CLOSE10",
        "CLOSE9",
        "CLOSE8",
        "CLOSE7",
        "CLOSE6",
        "CLOSE5",
        "CLOSE4",
        "CLOSE3",
        "CLOSE2",
        "CLOSE1",
        "CLOSE0",
        "OPEN59",
        "OPEN58",
        "OPEN57",
        "OPEN56",
        "OPEN55",
        "OPEN54",
        "OPEN53",
        "OPEN52",
        "OPEN51",
        "OPEN50",
        "OPEN49",
        "OPEN48",
        "OPEN47",
        "OPEN46",
        "OPEN45",
        "OPEN44",
        "OPEN43",
        "OPEN42",
        "OPEN41",
        "OPEN40",
        "OPEN39",
        "OPEN38",
        "OPEN37",
        "OPEN36",
        "OPEN35",
        "OPEN34",
        "OPEN33",
        "OPEN32",
        "OPEN31",
        "OPEN30",
        "OPEN29",
        "OPEN28",
        "OPEN27",
        "OPEN26",
        "OPEN25",
        "OPEN24",
        "OPEN23",
        "OPEN22",
        "OPEN21",
        "OPEN20",
        "OPEN19",
        "OPEN18",
        "OPEN17",
        "OPEN16",
        "OPEN15",
        "OPEN14",
        "OPEN13",
        "OPEN12",
        "OPEN11",
        "OPEN10",
        "OPEN9",
        "OPEN8",
        "OPEN7",
        "OPEN6",
        "OPEN5",
        "OPEN4",
        "OPEN3",
        "OPEN2",
        "OPEN1",
        "OPEN0",
        "HIGH59",
        "HIGH58",
        "HIGH57",
        "HIGH56",
        "HIGH55",
        "HIGH54",
        "HIGH53",
        "HIGH52",
        "HIGH51",
        "HIGH50",
        "HIGH49",
        "HIGH48",
        "HIGH47",
        "HIGH46",
        "HIGH45",
        "HIGH44",
        "HIGH43",
        "HIGH42",
        "HIGH41",
        "HIGH40",
        "HIGH39",
        "HIGH38",
        "HIGH37",
        "HIGH36",
        "HIGH35",
        "HIGH34",
        "HIGH33",
        "HIGH32",
        "HIGH31",
        "HIGH30",
        "HIGH29",
        "HIGH28",
        "HIGH27",
        "HIGH26",
        "HIGH25",
        "HIGH24",
        "HIGH23",
        "HIGH22",
        "HIGH21",
        "HIGH20",
        "HIGH19",
        "HIGH18",
        "HIGH17",
        "HIGH16",
        "HIGH15",
        "HIGH14",
        "HIGH13",
        "HIGH12",
        "HIGH11",
        "HIGH10",
        "HIGH9",
        "HIGH8",
        "HIGH7",
        "HIGH6",
        "HIGH5",
        "HIGH4",
        "HIGH3",
        "HIGH2",
        "HIGH1",
        "HIGH0",
        "LOW59",
        "LOW58",
        "LOW57",
        "LOW56",
        "LOW55",
        "LOW54",
        "LOW53",
        "LOW52",
        "LOW51",
        "LOW50",
        "LOW49",
        "LOW48",
        "LOW47",
        "LOW46",
        "LOW45",
        "LOW44",
        "LOW43",
        "LOW42",
        "LOW41",
        "LOW40",
        "LOW39",
        "LOW38",
        "LOW37",
        "LOW36",
        "LOW35",
        "LOW34",
        "LOW33",
        "LOW32",
        "LOW31",
        "LOW30",
        "LOW29",
        "LOW28",
        "LOW27",
        "LOW26",
        "LOW25",
        "LOW24",
        "LOW23",
        "LOW22",
        "LOW21",
        "LOW20",
        "LOW19",
        "LOW18",
        "LOW17",
        "LOW16",
        "LOW15",
        "LOW14",
        "LOW13",
        "LOW12",
        "LOW11",
        "LOW10",
        "LOW9",
        "LOW8",
        "LOW7",
        "LOW6",
        "LOW5",
        "LOW4",
        "LOW3",
        "LOW2",
        "LOW1",
        "LOW0",
        "VWAP59",
        "VWAP58",
        "VWAP57",
        "VWAP56",
        "VWAP55",
        "VWAP54",
        "VWAP53",
        "VWAP52",
        "VWAP51",
        "VWAP50",
        "VWAP49",
        "VWAP48",
        "VWAP47",
        "VWAP46",
        "VWAP45",
        "VWAP44",
        "VWAP43",
        "VWAP42",
        "VWAP41",
        "VWAP40",
        "VWAP39",
        "VWAP38",
        "VWAP37",
        "VWAP36",
        "VWAP35",
        "VWAP34",
        "VWAP33",
        "VWAP32",
        "VWAP31",
        "VWAP30",
        "VWAP29",
        "VWAP28",
        "VWAP27",
        "VWAP26",
        "VWAP25",
        "VWAP24",
        "VWAP23",
        "VWAP22",
        "VWAP21",
        "VWAP20",
        "VWAP19",
        "VWAP18",
        "VWAP17",
        "VWAP16",
        "VWAP15",
        "VWAP14",
        "VWAP13",
        "VWAP12",
        "VWAP11",
        "VWAP10",
        "VWAP9",
        "VWAP8",
        "VWAP7",
        "VWAP6",
        "VWAP5",
        "VWAP4",
        "VWAP3",
        "VWAP2",
        "VWAP1",
        "VWAP0",
        "VOLUME59",
        "VOLUME58",
        "VOLUME57",
        "VOLUME56",
        "VOLUME55",
        "VOLUME54",
        "VOLUME53",
        "VOLUME52",
        "VOLUME51",
        "VOLUME50",
        "VOLUME49",
        "VOLUME48",
        "VOLUME47",
        "VOLUME46",
        "VOLUME45",
        "VOLUME44",
        "VOLUME43",
        "VOLUME42",
        "VOLUME41",
        "VOLUME40",
        "VOLUME39",
        "VOLUME38",
        "VOLUME37",
        "VOLUME36",
        "VOLUME35",
        "VOLUME34",
        "VOLUME33",
        "VOLUME32",
        "VOLUME31",
        "VOLUME30",
        "VOLUME29",
        "VOLUME28",
        "VOLUME27",
        "VOLUME26",
        "VOLUME25",
        "VOLUME24",
        "VOLUME23",
        "VOLUME22",
        "VOLUME21",
        "VOLUME20",
        "VOLUME19",
        "VOLUME18",
        "VOLUME17",
        "VOLUME16",
        "VOLUME15",
        "VOLUME14",
        "VOLUME13",
        "VOLUME12",
        "VOLUME11",
        "VOLUME10",
        "VOLUME9",
        "VOLUME8",
        "VOLUME7",
        "VOLUME6",
        "VOLUME5",
        "VOLUME4",
        "VOLUME3",
        "VOLUME2",
        "VOLUME1",
        "VOLUME0",
    ],
)

assert len(cfg[0]) == len(cfg[1])
cfg_dict = [
    {"formula": formula, "name": f"qlib360_{name}"} for formula, name in zip(cfg[0], cfg[1])
]

print(cfg_dict)

alpha_cfg = Alpha158DL.get_feature_config()

print(alpha_cfg)

cfg158 = (
    [
        "($close-$open)/$open",
        "($high-$low)/$open",
        "($close-$open)/($high-$low+1e-12)",
        "($high-Greater($open, $close))/$open",
        "($high-Greater($open, $close))/($high-$low+1e-12)",
        "(Less($open, $close)-$low)/$open",
        "(Less($open, $close)-$low)/($high-$low+1e-12)",
        "(2*$close-$high-$low)/$open",
        "(2*$close-$high-$low)/($high-$low+1e-12)",
        "$open/$close",
        "$high/$close",
        "$low/$close",
        "$vwap/$close",
        "Delay($close, 5)/$close",
        "Delay($close, 10)/$close",
        "Delay($close, 20)/$close",
        "Delay($close, 30)/$close",
        "Delay($close, 60)/$close",
        "Mean($close, 5)/$close",
        "Mean($close, 10)/$close",
        "Mean($close, 20)/$close",
        "Mean($close, 30)/$close",
        "Mean($close, 60)/$close",
        "Std($close, 5)/$close",
        "Std($close, 10)/$close",
        "Std($close, 20)/$close",
        "Std($close, 30)/$close",
        "Std($close, 60)/$close",
        "Slope($close, 5)/$close",
        "Slope($close, 10)/$close",
        "Slope($close, 20)/$close",
        "Slope($close, 30)/$close",
        "Slope($close, 60)/$close",
        "Rsquare($close, 5)",
        "Rsquare($close, 10)",
        "Rsquare($close, 20)",
        "Rsquare($close, 30)",
        "Rsquare($close, 60)",
        "Resi($close, 5)/$close",
        "Resi($close, 10)/$close",
        "Resi($close, 20)/$close",
        "Resi($close, 30)/$close",
        "Resi($close, 60)/$close",
        "Max($high, 5)/$close",
        "Max($high, 10)/$close",
        "Max($high, 20)/$close",
        "Max($high, 30)/$close",
        "Max($high, 60)/$close",
        "Min($low, 5)/$close",
        "Min($low, 10)/$close",
        "Min($low, 20)/$close",
        "Min($low, 30)/$close",
        "Min($low, 60)/$close",
        "Quantile($close, 5, 0.8)/$close",
        "Quantile($close, 10, 0.8)/$close",
        "Quantile($close, 20, 0.8)/$close",
        "Quantile($close, 30, 0.8)/$close",
        "Quantile($close, 60, 0.8)/$close",
        "Quantile($close, 5, 0.2)/$close",
        "Quantile($close, 10, 0.2)/$close",
        "Quantile($close, 20, 0.2)/$close",
        "Quantile($close, 30, 0.2)/$close",
        "Quantile($close, 60, 0.2)/$close",
        "Rank($close, 5)",
        "Rank($close, 10)",
        "Rank($close, 20)",
        "Rank($close, 30)",
        "Rank($close, 60)",
        "($close-Min($low, 5))/(Max($high, 5)-Min($low, 5)+1e-12)",
        "($close-Min($low, 10))/(Max($high, 10)-Min($low, 10)+1e-12)",
        "($close-Min($low, 20))/(Max($high, 20)-Min($low, 20)+1e-12)",
        "($close-Min($low, 30))/(Max($high, 30)-Min($low, 30)+1e-12)",
        "($close-Min($low, 60))/(Max($high, 60)-Min($low, 60)+1e-12)",
        "IdxMax($high, 5)/5",
        "IdxMax($high, 10)/10",
        "IdxMax($high, 20)/20",
        "IdxMax($high, 30)/30",
        "IdxMax($high, 60)/60",
        "IdxMin($low, 5)/5",
        "IdxMin($low, 10)/10",
        "IdxMin($low, 20)/20",
        "IdxMin($low, 30)/30",
        "IdxMin($low, 60)/60",
        "(IdxMax($high, 5)-IdxMin($low, 5))/5",
        "(IdxMax($high, 10)-IdxMin($low, 10))/10",
        "(IdxMax($high, 20)-IdxMin($low, 20))/20",
        "(IdxMax($high, 30)-IdxMin($low, 30))/30",
        "(IdxMax($high, 60)-IdxMin($low, 60))/60",
        "Corr($close, Log($volume+1), 5)",
        "Corr($close, Log($volume+1), 10)",
        "Corr($close, Log($volume+1), 20)",
        "Corr($close, Log($volume+1), 30)",
        "Corr($close, Log($volume+1), 60)",
        "Corr($close/Delay($close,1), Log($volume/Delay($volume, 1)+1), 5)",
        "Corr($close/Delay($close,1), Log($volume/Delay($volume, 1)+1), 10)",
        "Corr($close/Delay($close,1), Log($volume/Delay($volume, 1)+1), 20)",
        "Corr($close/Delay($close,1), Log($volume/Delay($volume, 1)+1), 30)",
        "Corr($close/Delay($close,1), Log($volume/Delay($volume, 1)+1), 60)",
        "Mean($close>Delay($close, 1), 5)",
        "Mean($close>Delay($close, 1), 10)",
        "Mean($close>Delay($close, 1), 20)",
        "Mean($close>Delay($close, 1), 30)",
        "Mean($close>Delay($close, 1), 60)",
        "Mean($close<Delay($close, 1), 5)",
        "Mean($close<Delay($close, 1), 10)",
        "Mean($close<Delay($close, 1), 20)",
        "Mean($close<Delay($close, 1), 30)",
        "Mean($close<Delay($close, 1), 60)",
        "Mean($close>Delay($close, 1), 5)-Mean($close<Delay($close, 1), 5)",
        "Mean($close>Delay($close, 1), 10)-Mean($close<Delay($close, 1), 10)",
        "Mean($close>Delay($close, 1), 20)-Mean($close<Delay($close, 1), 20)",
        "Mean($close>Delay($close, 1), 30)-Mean($close<Delay($close, 1), 30)",
        "Mean($close>Delay($close, 1), 60)-Mean($close<Delay($close, 1), 60)",
        "Sum(Greater($close-Delay($close, 1), 0), 5)/(Sum(Abs($close-Delay($close, 1)), 5)+1e-12)",
        "Sum(Greater($close-Delay($close, 1), 0), 10)/(Sum(Abs($close-Delay($close, 1)), 10)+1e-12)",
        "Sum(Greater($close-Delay($close, 1), 0), 20)/(Sum(Abs($close-Delay($close, 1)), 20)+1e-12)",
        "Sum(Greater($close-Delay($close, 1), 0), 30)/(Sum(Abs($close-Delay($close, 1)), 30)+1e-12)",
        "Sum(Greater($close-Delay($close, 1), 0), 60)/(Sum(Abs($close-Delay($close, 1)), 60)+1e-12)",
        "Sum(Greater(Delay($close, 1)-$close, 0), 5)/(Sum(Abs($close-Delay($close, 1)), 5)+1e-12)",
        "Sum(Greater(Delay($close, 1)-$close, 0), 10)/(Sum(Abs($close-Delay($close, 1)), 10)+1e-12)",
        "Sum(Greater(Delay($close, 1)-$close, 0), 20)/(Sum(Abs($close-Delay($close, 1)), 20)+1e-12)",
        "Sum(Greater(Delay($close, 1)-$close, 0), 30)/(Sum(Abs($close-Delay($close, 1)), 30)+1e-12)",
        "Sum(Greater(Delay($close, 1)-$close, 0), 60)/(Sum(Abs($close-Delay($close, 1)), 60)+1e-12)",
        "(Sum(Greater($close-Delay($close, 1), 0), 5)-Sum(Greater(Delay($close, 1)-$close, 0), 5))/(Sum(Abs($close-Delay($close, 1)), 5)+1e-12)",
        "(Sum(Greater($close-Delay($close, 1), 0), 10)-Sum(Greater(Delay($close, 1)-$close, 0), 10))/(Sum(Abs($close-Delay($close, 1)), 10)+1e-12)",
        "(Sum(Greater($close-Delay($close, 1), 0), 20)-Sum(Greater(Delay($close, 1)-$close, 0), 20))/(Sum(Abs($close-Delay($close, 1)), 20)+1e-12)",
        "(Sum(Greater($close-Delay($close, 1), 0), 30)-Sum(Greater(Delay($close, 1)-$close, 0), 30))/(Sum(Abs($close-Delay($close, 1)), 30)+1e-12)",
        "(Sum(Greater($close-Delay($close, 1), 0), 60)-Sum(Greater(Delay($close, 1)-$close, 0), 60))/(Sum(Abs($close-Delay($close, 1)), 60)+1e-12)",
        "Mean($volume, 5)/($volume+1e-12)",
        "Mean($volume, 10)/($volume+1e-12)",
        "Mean($volume, 20)/($volume+1e-12)",
        "Mean($volume, 30)/($volume+1e-12)",
        "Mean($volume, 60)/($volume+1e-12)",
        "Std($volume, 5)/($volume+1e-12)",
        "Std($volume, 10)/($volume+1e-12)",
        "Std($volume, 20)/($volume+1e-12)",
        "Std($volume, 30)/($volume+1e-12)",
        "Std($volume, 60)/($volume+1e-12)",
        "Std(Abs($close/Delay($close, 1)-1)*$volume, 5)/(Mean(Abs($close/Delay($close, 1)-1)*$volume, 5)+1e-12)",
        "Std(Abs($close/Delay($close, 1)-1)*$volume, 10)/(Mean(Abs($close/Delay($close, 1)-1)*$volume, 10)+1e-12)",
        "Std(Abs($close/Delay($close, 1)-1)*$volume, 20)/(Mean(Abs($close/Delay($close, 1)-1)*$volume, 20)+1e-12)",
        "Std(Abs($close/Delay($close, 1)-1)*$volume, 30)/(Mean(Abs($close/Delay($close, 1)-1)*$volume, 30)+1e-12)",
        "Std(Abs($close/Delay($close, 1)-1)*$volume, 60)/(Mean(Abs($close/Delay($close, 1)-1)*$volume, 60)+1e-12)",
        "Sum(Greater($volume-Delay($volume, 1), 0), 5)/(Sum(Abs($volume-Delay($volume, 1)), 5)+1e-12)",
        "Sum(Greater($volume-Delay($volume, 1), 0), 10)/(Sum(Abs($volume-Delay($volume, 1)), 10)+1e-12)",
        "Sum(Greater($volume-Delay($volume, 1), 0), 20)/(Sum(Abs($volume-Delay($volume, 1)), 20)+1e-12)",
        "Sum(Greater($volume-Delay($volume, 1), 0), 30)/(Sum(Abs($volume-Delay($volume, 1)), 30)+1e-12)",
        "Sum(Greater($volume-Delay($volume, 1), 0), 60)/(Sum(Abs($volume-Delay($volume, 1)), 60)+1e-12)",
        "Sum(Greater(Delay($volume, 1)-$volume, 0), 5)/(Sum(Abs($volume-Delay($volume, 1)), 5)+1e-12)",
        "Sum(Greater(Delay($volume, 1)-$volume, 0), 10)/(Sum(Abs($volume-Delay($volume, 1)), 10)+1e-12)",
        "Sum(Greater(Delay($volume, 1)-$volume, 0), 20)/(Sum(Abs($volume-Delay($volume, 1)), 20)+1e-12)",
        "Sum(Greater(Delay($volume, 1)-$volume, 0), 30)/(Sum(Abs($volume-Delay($volume, 1)), 30)+1e-12)",
        "Sum(Greater(Delay($volume, 1)-$volume, 0), 60)/(Sum(Abs($volume-Delay($volume, 1)), 60)+1e-12)",
        "(Sum(Greater($volume-Delay($volume, 1), 0), 5)-Sum(Greater(Delay($volume, 1)-$volume, 0), 5))/(Sum(Abs($volume-Delay($volume, 1)), 5)+1e-12)",
        "(Sum(Greater($volume-Delay($volume, 1), 0), 10)-Sum(Greater(Delay($volume, 1)-$volume, 0), 10))/(Sum(Abs($volume-Delay($volume, 1)), 10)+1e-12)",
        "(Sum(Greater($volume-Delay($volume, 1), 0), 20)-Sum(Greater(Delay($volume, 1)-$volume, 0), 20))/(Sum(Abs($volume-Delay($volume, 1)), 20)+1e-12)",
        "(Sum(Greater($volume-Delay($volume, 1), 0), 30)-Sum(Greater(Delay($volume, 1)-$volume, 0), 30))/(Sum(Abs($volume-Delay($volume, 1)), 30)+1e-12)",
        "(Sum(Greater($volume-Delay($volume, 1), 0), 60)-Sum(Greater(Delay($volume, 1)-$volume, 0), 60))/(Sum(Abs($volume-Delay($volume, 1)), 60)+1e-12)",
    ],
    [
        "KMID",
        "KLEN",
        "KMID2",
        "KUP",
        "KUP2",
        "KLOW",
        "KLOW2",
        "KSFT",
        "KSFT2",
        "OPEN0",
        "HIGH0",
        "LOW0",
        "VWAP0",
        "ROC5",
        "ROC10",
        "ROC20",
        "ROC30",
        "ROC60",
        "MA5",
        "MA10",
        "MA20",
        "MA30",
        "MA60",
        "STD5",
        "STD10",
        "STD20",
        "STD30",
        "STD60",
        "BETA5",
        "BETA10",
        "BETA20",
        "BETA30",
        "BETA60",
        "RSQR5",
        "RSQR10",
        "RSQR20",
        "RSQR30",
        "RSQR60",
        "RESI5",
        "RESI10",
        "RESI20",
        "RESI30",
        "RESI60",
        "MAX5",
        "MAX10",
        "MAX20",
        "MAX30",
        "MAX60",
        "MIN5",
        "MIN10",
        "MIN20",
        "MIN30",
        "MIN60",
        "QTLU5",
        "QTLU10",
        "QTLU20",
        "QTLU30",
        "QTLU60",
        "QTLD5",
        "QTLD10",
        "QTLD20",
        "QTLD30",
        "QTLD60",
        "RANK5",
        "RANK10",
        "RANK20",
        "RANK30",
        "RANK60",
        "RSV5",
        "RSV10",
        "RSV20",
        "RSV30",
        "RSV60",
        "IMAX5",
        "IMAX10",
        "IMAX20",
        "IMAX30",
        "IMAX60",
        "IMIN5",
        "IMIN10",
        "IMIN20",
        "IMIN30",
        "IMIN60",
        "IMXD5",
        "IMXD10",
        "IMXD20",
        "IMXD30",
        "IMXD60",
        "CORR5",
        "CORR10",
        "CORR20",
        "CORR30",
        "CORR60",
        "CORD5",
        "CORD10",
        "CORD20",
        "CORD30",
        "CORD60",
        "CNTP5",
        "CNTP10",
        "CNTP20",
        "CNTP30",
        "CNTP60",
        "CNTN5",
        "CNTN10",
        "CNTN20",
        "CNTN30",
        "CNTN60",
        "CNTD5",
        "CNTD10",
        "CNTD20",
        "CNTD30",
        "CNTD60",
        "SUMP5",
        "SUMP10",
        "SUMP20",
        "SUMP30",
        "SUMP60",
        "SUMN5",
        "SUMN10",
        "SUMN20",
        "SUMN30",
        "SUMN60",
        "SUMD5",
        "SUMD10",
        "SUMD20",
        "SUMD30",
        "SUMD60",
        "VMA5",
        "VMA10",
        "VMA20",
        "VMA30",
        "VMA60",
        "VSTD5",
        "VSTD10",
        "VSTD20",
        "VSTD30",
        "VSTD60",
        "WVMA5",
        "WVMA10",
        "WVMA20",
        "WVMA30",
        "WVMA60",
        "VSUMP5",
        "VSUMP10",
        "VSUMP20",
        "VSUMP30",
        "VSUMP60",
        "VSUMN5",
        "VSUMN10",
        "VSUMN20",
        "VSUMN30",
        "VSUMN60",
        "VSUMD5",
        "VSUMD10",
        "VSUMD20",
        "VSUMD30",
        "VSUMD60",
    ],
)


assert len(cfg158[0]) == len(cfg158[1])
cfg_dict2 = [
    {"formula": formula, "name": f"qlib158_{name}"} for formula, name in zip(cfg158[0], cfg158[1])
]

print(cfg_dict2)
"""

from factorminer.benchmark.catalogs import CandidateEntry
from factorminer.core.infix_translator import to_prefix_dsl


def build_qlib360() -> list[CandidateEntry]:
    qlib_alpha360 = [
        {"formula": "Div(Delay($close, 59), $close)", "name": "qlib360_CLOSE59"},
        {"formula": "Div(Delay($close, 58), $close)", "name": "qlib360_CLOSE58"},
        {"formula": "Div(Delay($close, 57), $close)", "name": "qlib360_CLOSE57"},
        {"formula": "Div(Delay($close, 56), $close)", "name": "qlib360_CLOSE56"},
        {"formula": "Div(Delay($close, 55), $close)", "name": "qlib360_CLOSE55"},
        {"formula": "Div(Delay($close, 54), $close)", "name": "qlib360_CLOSE54"},
        {"formula": "Div(Delay($close, 53), $close)", "name": "qlib360_CLOSE53"},
        {"formula": "Div(Delay($close, 52), $close)", "name": "qlib360_CLOSE52"},
        {"formula": "Div(Delay($close, 51), $close)", "name": "qlib360_CLOSE51"},
        {"formula": "Div(Delay($close, 50), $close)", "name": "qlib360_CLOSE50"},
        {"formula": "Div(Delay($close, 49), $close)", "name": "qlib360_CLOSE49"},
        {"formula": "Div(Delay($close, 48), $close)", "name": "qlib360_CLOSE48"},
        {"formula": "Div(Delay($close, 47), $close)", "name": "qlib360_CLOSE47"},
        {"formula": "Div(Delay($close, 46), $close)", "name": "qlib360_CLOSE46"},
        {"formula": "Div(Delay($close, 45), $close)", "name": "qlib360_CLOSE45"},
        {"formula": "Div(Delay($close, 44), $close)", "name": "qlib360_CLOSE44"},
        {"formula": "Div(Delay($close, 43), $close)", "name": "qlib360_CLOSE43"},
        {"formula": "Div(Delay($close, 42), $close)", "name": "qlib360_CLOSE42"},
        {"formula": "Div(Delay($close, 41), $close)", "name": "qlib360_CLOSE41"},
        {"formula": "Div(Delay($close, 40), $close)", "name": "qlib360_CLOSE40"},
        {"formula": "Div(Delay($close, 39), $close)", "name": "qlib360_CLOSE39"},
        {"formula": "Div(Delay($close, 38), $close)", "name": "qlib360_CLOSE38"},
        {"formula": "Div(Delay($close, 37), $close)", "name": "qlib360_CLOSE37"},
        {"formula": "Div(Delay($close, 36), $close)", "name": "qlib360_CLOSE36"},
        {"formula": "Div(Delay($close, 35), $close)", "name": "qlib360_CLOSE35"},
        {"formula": "Div(Delay($close, 34), $close)", "name": "qlib360_CLOSE34"},
        {"formula": "Div(Delay($close, 33), $close)", "name": "qlib360_CLOSE33"},
        {"formula": "Div(Delay($close, 32), $close)", "name": "qlib360_CLOSE32"},
        {"formula": "Div(Delay($close, 31), $close)", "name": "qlib360_CLOSE31"},
        {"formula": "Div(Delay($close, 30), $close)", "name": "qlib360_CLOSE30"},
        {"formula": "Div(Delay($close, 29), $close)", "name": "qlib360_CLOSE29"},
        {"formula": "Div(Delay($close, 28), $close)", "name": "qlib360_CLOSE28"},
        {"formula": "Div(Delay($close, 27), $close)", "name": "qlib360_CLOSE27"},
        {"formula": "Div(Delay($close, 26), $close)", "name": "qlib360_CLOSE26"},
        {"formula": "Div(Delay($close, 25), $close)", "name": "qlib360_CLOSE25"},
        {"formula": "Div(Delay($close, 24), $close)", "name": "qlib360_CLOSE24"},
        {"formula": "Div(Delay($close, 23), $close)", "name": "qlib360_CLOSE23"},
        {"formula": "Div(Delay($close, 22), $close)", "name": "qlib360_CLOSE22"},
        {"formula": "Div(Delay($close, 21), $close)", "name": "qlib360_CLOSE21"},
        {"formula": "Div(Delay($close, 20), $close)", "name": "qlib360_CLOSE20"},
        {"formula": "Div(Delay($close, 19), $close)", "name": "qlib360_CLOSE19"},
        {"formula": "Div(Delay($close, 18), $close)", "name": "qlib360_CLOSE18"},
        {"formula": "Div(Delay($close, 17), $close)", "name": "qlib360_CLOSE17"},
        {"formula": "Div(Delay($close, 16), $close)", "name": "qlib360_CLOSE16"},
        {"formula": "Div(Delay($close, 15), $close)", "name": "qlib360_CLOSE15"},
        {"formula": "Div(Delay($close, 14), $close)", "name": "qlib360_CLOSE14"},
        {"formula": "Div(Delay($close, 13), $close)", "name": "qlib360_CLOSE13"},
        {"formula": "Div(Delay($close, 12), $close)", "name": "qlib360_CLOSE12"},
        {"formula": "Div(Delay($close, 11), $close)", "name": "qlib360_CLOSE11"},
        {"formula": "Div(Delay($close, 10), $close)", "name": "qlib360_CLOSE10"},
        {"formula": "Div(Delay($close, 9), $close)", "name": "qlib360_CLOSE9"},
        {"formula": "Div(Delay($close, 8), $close)", "name": "qlib360_CLOSE8"},
        {"formula": "Div(Delay($close, 7), $close)", "name": "qlib360_CLOSE7"},
        {"formula": "Div(Delay($close, 6), $close)", "name": "qlib360_CLOSE6"},
        {"formula": "Div(Delay($close, 5), $close)", "name": "qlib360_CLOSE5"},
        {"formula": "Div(Delay($close, 4), $close)", "name": "qlib360_CLOSE4"},
        {"formula": "Div(Delay($close, 3), $close)", "name": "qlib360_CLOSE3"},
        {"formula": "Div(Delay($close, 2), $close)", "name": "qlib360_CLOSE2"},
        {"formula": "Div(Delay($close, 1), $close)", "name": "qlib360_CLOSE1"},
        {"formula": "Div($close, $close)", "name": "qlib360_CLOSE0"},
        {"formula": "Div(Delay($open, 59), $close)", "name": "qlib360_OPEN59"},
        {"formula": "Div(Delay($open, 58), $close)", "name": "qlib360_OPEN58"},
        {"formula": "Div(Delay($open, 57), $close)", "name": "qlib360_OPEN57"},
        {"formula": "Div(Delay($open, 56), $close)", "name": "qlib360_OPEN56"},
        {"formula": "Div(Delay($open, 55), $close)", "name": "qlib360_OPEN55"},
        {"formula": "Div(Delay($open, 54), $close)", "name": "qlib360_OPEN54"},
        {"formula": "Div(Delay($open, 53), $close)", "name": "qlib360_OPEN53"},
        {"formula": "Div(Delay($open, 52), $close)", "name": "qlib360_OPEN52"},
        {"formula": "Div(Delay($open, 51), $close)", "name": "qlib360_OPEN51"},
        {"formula": "Div(Delay($open, 50), $close)", "name": "qlib360_OPEN50"},
        {"formula": "Div(Delay($open, 49), $close)", "name": "qlib360_OPEN49"},
        {"formula": "Div(Delay($open, 48), $close)", "name": "qlib360_OPEN48"},
        {"formula": "Div(Delay($open, 47), $close)", "name": "qlib360_OPEN47"},
        {"formula": "Div(Delay($open, 46), $close)", "name": "qlib360_OPEN46"},
        {"formula": "Div(Delay($open, 45), $close)", "name": "qlib360_OPEN45"},
        {"formula": "Div(Delay($open, 44), $close)", "name": "qlib360_OPEN44"},
        {"formula": "Div(Delay($open, 43), $close)", "name": "qlib360_OPEN43"},
        {"formula": "Div(Delay($open, 42), $close)", "name": "qlib360_OPEN42"},
        {"formula": "Div(Delay($open, 41), $close)", "name": "qlib360_OPEN41"},
        {"formula": "Div(Delay($open, 40), $close)", "name": "qlib360_OPEN40"},
        {"formula": "Div(Delay($open, 39), $close)", "name": "qlib360_OPEN39"},
        {"formula": "Div(Delay($open, 38), $close)", "name": "qlib360_OPEN38"},
        {"formula": "Div(Delay($open, 37), $close)", "name": "qlib360_OPEN37"},
        {"formula": "Div(Delay($open, 36), $close)", "name": "qlib360_OPEN36"},
        {"formula": "Div(Delay($open, 35), $close)", "name": "qlib360_OPEN35"},
        {"formula": "Div(Delay($open, 34), $close)", "name": "qlib360_OPEN34"},
        {"formula": "Div(Delay($open, 33), $close)", "name": "qlib360_OPEN33"},
        {"formula": "Div(Delay($open, 32), $close)", "name": "qlib360_OPEN32"},
        {"formula": "Div(Delay($open, 31), $close)", "name": "qlib360_OPEN31"},
        {"formula": "Div(Delay($open, 30), $close)", "name": "qlib360_OPEN30"},
        {"formula": "Div(Delay($open, 29), $close)", "name": "qlib360_OPEN29"},
        {"formula": "Div(Delay($open, 28), $close)", "name": "qlib360_OPEN28"},
        {"formula": "Div(Delay($open, 27), $close)", "name": "qlib360_OPEN27"},
        {"formula": "Div(Delay($open, 26), $close)", "name": "qlib360_OPEN26"},
        {"formula": "Div(Delay($open, 25), $close)", "name": "qlib360_OPEN25"},
        {"formula": "Div(Delay($open, 24), $close)", "name": "qlib360_OPEN24"},
        {"formula": "Div(Delay($open, 23), $close)", "name": "qlib360_OPEN23"},
        {"formula": "Div(Delay($open, 22), $close)", "name": "qlib360_OPEN22"},
        {"formula": "Div(Delay($open, 21), $close)", "name": "qlib360_OPEN21"},
        {"formula": "Div(Delay($open, 20), $close)", "name": "qlib360_OPEN20"},
        {"formula": "Div(Delay($open, 19), $close)", "name": "qlib360_OPEN19"},
        {"formula": "Div(Delay($open, 18), $close)", "name": "qlib360_OPEN18"},
        {"formula": "Div(Delay($open, 17), $close)", "name": "qlib360_OPEN17"},
        {"formula": "Div(Delay($open, 16), $close)", "name": "qlib360_OPEN16"},
        {"formula": "Div(Delay($open, 15), $close)", "name": "qlib360_OPEN15"},
        {"formula": "Div(Delay($open, 14), $close)", "name": "qlib360_OPEN14"},
        {"formula": "Div(Delay($open, 13), $close)", "name": "qlib360_OPEN13"},
        {"formula": "Div(Delay($open, 12), $close)", "name": "qlib360_OPEN12"},
        {"formula": "Div(Delay($open, 11), $close)", "name": "qlib360_OPEN11"},
        {"formula": "Div(Delay($open, 10), $close)", "name": "qlib360_OPEN10"},
        {"formula": "Div(Delay($open, 9), $close)", "name": "qlib360_OPEN9"},
        {"formula": "Div(Delay($open, 8), $close)", "name": "qlib360_OPEN8"},
        {"formula": "Div(Delay($open, 7), $close)", "name": "qlib360_OPEN7"},
        {"formula": "Div(Delay($open, 6), $close)", "name": "qlib360_OPEN6"},
        {"formula": "Div(Delay($open, 5), $close)", "name": "qlib360_OPEN5"},
        {"formula": "Div(Delay($open, 4), $close)", "name": "qlib360_OPEN4"},
        {"formula": "Div(Delay($open, 3), $close)", "name": "qlib360_OPEN3"},
        {"formula": "Div(Delay($open, 2), $close)", "name": "qlib360_OPEN2"},
        {"formula": "Div(Delay($open, 1), $close)", "name": "qlib360_OPEN1"},
        {"formula": "Div($open, $close)", "name": "qlib360_OPEN0"},
        {"formula": "Div(Delay($high, 59), $close)", "name": "qlib360_HIGH59"},
        {"formula": "Div(Delay($high, 58), $close)", "name": "qlib360_HIGH58"},
        {"formula": "Div(Delay($high, 57), $close)", "name": "qlib360_HIGH57"},
        {"formula": "Div(Delay($high, 56), $close)", "name": "qlib360_HIGH56"},
        {"formula": "Div(Delay($high, 55), $close)", "name": "qlib360_HIGH55"},
        {"formula": "Div(Delay($high, 54), $close)", "name": "qlib360_HIGH54"},
        {"formula": "Div(Delay($high, 53), $close)", "name": "qlib360_HIGH53"},
        {"formula": "Div(Delay($high, 52), $close)", "name": "qlib360_HIGH52"},
        {"formula": "Div(Delay($high, 51), $close)", "name": "qlib360_HIGH51"},
        {"formula": "Div(Delay($high, 50), $close)", "name": "qlib360_HIGH50"},
        {"formula": "Div(Delay($high, 49), $close)", "name": "qlib360_HIGH49"},
        {"formula": "Div(Delay($high, 48), $close)", "name": "qlib360_HIGH48"},
        {"formula": "Div(Delay($high, 47), $close)", "name": "qlib360_HIGH47"},
        {"formula": "Div(Delay($high, 46), $close)", "name": "qlib360_HIGH46"},
        {"formula": "Div(Delay($high, 45), $close)", "name": "qlib360_HIGH45"},
        {"formula": "Div(Delay($high, 44), $close)", "name": "qlib360_HIGH44"},
        {"formula": "Div(Delay($high, 43), $close)", "name": "qlib360_HIGH43"},
        {"formula": "Div(Delay($high, 42), $close)", "name": "qlib360_HIGH42"},
        {"formula": "Div(Delay($high, 41), $close)", "name": "qlib360_HIGH41"},
        {"formula": "Div(Delay($high, 40), $close)", "name": "qlib360_HIGH40"},
        {"formula": "Div(Delay($high, 39), $close)", "name": "qlib360_HIGH39"},
        {"formula": "Div(Delay($high, 38), $close)", "name": "qlib360_HIGH38"},
        {"formula": "Div(Delay($high, 37), $close)", "name": "qlib360_HIGH37"},
        {"formula": "Div(Delay($high, 36), $close)", "name": "qlib360_HIGH36"},
        {"formula": "Div(Delay($high, 35), $close)", "name": "qlib360_HIGH35"},
        {"formula": "Div(Delay($high, 34), $close)", "name": "qlib360_HIGH34"},
        {"formula": "Div(Delay($high, 33), $close)", "name": "qlib360_HIGH33"},
        {"formula": "Div(Delay($high, 32), $close)", "name": "qlib360_HIGH32"},
        {"formula": "Div(Delay($high, 31), $close)", "name": "qlib360_HIGH31"},
        {"formula": "Div(Delay($high, 30), $close)", "name": "qlib360_HIGH30"},
        {"formula": "Div(Delay($high, 29), $close)", "name": "qlib360_HIGH29"},
        {"formula": "Div(Delay($high, 28), $close)", "name": "qlib360_HIGH28"},
        {"formula": "Div(Delay($high, 27), $close)", "name": "qlib360_HIGH27"},
        {"formula": "Div(Delay($high, 26), $close)", "name": "qlib360_HIGH26"},
        {"formula": "Div(Delay($high, 25), $close)", "name": "qlib360_HIGH25"},
        {"formula": "Div(Delay($high, 24), $close)", "name": "qlib360_HIGH24"},
        {"formula": "Div(Delay($high, 23), $close)", "name": "qlib360_HIGH23"},
        {"formula": "Div(Delay($high, 22), $close)", "name": "qlib360_HIGH22"},
        {"formula": "Div(Delay($high, 21), $close)", "name": "qlib360_HIGH21"},
        {"formula": "Div(Delay($high, 20), $close)", "name": "qlib360_HIGH20"},
        {"formula": "Div(Delay($high, 19), $close)", "name": "qlib360_HIGH19"},
        {"formula": "Div(Delay($high, 18), $close)", "name": "qlib360_HIGH18"},
        {"formula": "Div(Delay($high, 17), $close)", "name": "qlib360_HIGH17"},
        {"formula": "Div(Delay($high, 16), $close)", "name": "qlib360_HIGH16"},
        {"formula": "Div(Delay($high, 15), $close)", "name": "qlib360_HIGH15"},
        {"formula": "Div(Delay($high, 14), $close)", "name": "qlib360_HIGH14"},
        {"formula": "Div(Delay($high, 13), $close)", "name": "qlib360_HIGH13"},
        {"formula": "Div(Delay($high, 12), $close)", "name": "qlib360_HIGH12"},
        {"formula": "Div(Delay($high, 11), $close)", "name": "qlib360_HIGH11"},
        {"formula": "Div(Delay($high, 10), $close)", "name": "qlib360_HIGH10"},
        {"formula": "Div(Delay($high, 9), $close)", "name": "qlib360_HIGH9"},
        {"formula": "Div(Delay($high, 8), $close)", "name": "qlib360_HIGH8"},
        {"formula": "Div(Delay($high, 7), $close)", "name": "qlib360_HIGH7"},
        {"formula": "Div(Delay($high, 6), $close)", "name": "qlib360_HIGH6"},
        {"formula": "Div(Delay($high, 5), $close)", "name": "qlib360_HIGH5"},
        {"formula": "Div(Delay($high, 4), $close)", "name": "qlib360_HIGH4"},
        {"formula": "Div(Delay($high, 3), $close)", "name": "qlib360_HIGH3"},
        {"formula": "Div(Delay($high, 2), $close)", "name": "qlib360_HIGH2"},
        {"formula": "Div(Delay($high, 1), $close)", "name": "qlib360_HIGH1"},
        {"formula": "Div($high, $close)", "name": "qlib360_HIGH0"},
        {"formula": "Div(Delay($low, 59), $close)", "name": "qlib360_LOW59"},
        {"formula": "Div(Delay($low, 58), $close)", "name": "qlib360_LOW58"},
        {"formula": "Div(Delay($low, 57), $close)", "name": "qlib360_LOW57"},
        {"formula": "Div(Delay($low, 56), $close)", "name": "qlib360_LOW56"},
        {"formula": "Div(Delay($low, 55), $close)", "name": "qlib360_LOW55"},
        {"formula": "Div(Delay($low, 54), $close)", "name": "qlib360_LOW54"},
        {"formula": "Div(Delay($low, 53), $close)", "name": "qlib360_LOW53"},
        {"formula": "Div(Delay($low, 52), $close)", "name": "qlib360_LOW52"},
        {"formula": "Div(Delay($low, 51), $close)", "name": "qlib360_LOW51"},
        {"formula": "Div(Delay($low, 50), $close)", "name": "qlib360_LOW50"},
        {"formula": "Div(Delay($low, 49), $close)", "name": "qlib360_LOW49"},
        {"formula": "Div(Delay($low, 48), $close)", "name": "qlib360_LOW48"},
        {"formula": "Div(Delay($low, 47), $close)", "name": "qlib360_LOW47"},
        {"formula": "Div(Delay($low, 46), $close)", "name": "qlib360_LOW46"},
        {"formula": "Div(Delay($low, 45), $close)", "name": "qlib360_LOW45"},
        {"formula": "Div(Delay($low, 44), $close)", "name": "qlib360_LOW44"},
        {"formula": "Div(Delay($low, 43), $close)", "name": "qlib360_LOW43"},
        {"formula": "Div(Delay($low, 42), $close)", "name": "qlib360_LOW42"},
        {"formula": "Div(Delay($low, 41), $close)", "name": "qlib360_LOW41"},
        {"formula": "Div(Delay($low, 40), $close)", "name": "qlib360_LOW40"},
        {"formula": "Div(Delay($low, 39), $close)", "name": "qlib360_LOW39"},
        {"formula": "Div(Delay($low, 38), $close)", "name": "qlib360_LOW38"},
        {"formula": "Div(Delay($low, 37), $close)", "name": "qlib360_LOW37"},
        {"formula": "Div(Delay($low, 36), $close)", "name": "qlib360_LOW36"},
        {"formula": "Div(Delay($low, 35), $close)", "name": "qlib360_LOW35"},
        {"formula": "Div(Delay($low, 34), $close)", "name": "qlib360_LOW34"},
        {"formula": "Div(Delay($low, 33), $close)", "name": "qlib360_LOW33"},
        {"formula": "Div(Delay($low, 32), $close)", "name": "qlib360_LOW32"},
        {"formula": "Div(Delay($low, 31), $close)", "name": "qlib360_LOW31"},
        {"formula": "Div(Delay($low, 30), $close)", "name": "qlib360_LOW30"},
        {"formula": "Div(Delay($low, 29), $close)", "name": "qlib360_LOW29"},
        {"formula": "Div(Delay($low, 28), $close)", "name": "qlib360_LOW28"},
        {"formula": "Div(Delay($low, 27), $close)", "name": "qlib360_LOW27"},
        {"formula": "Div(Delay($low, 26), $close)", "name": "qlib360_LOW26"},
        {"formula": "Div(Delay($low, 25), $close)", "name": "qlib360_LOW25"},
        {"formula": "Div(Delay($low, 24), $close)", "name": "qlib360_LOW24"},
        {"formula": "Div(Delay($low, 23), $close)", "name": "qlib360_LOW23"},
        {"formula": "Div(Delay($low, 22), $close)", "name": "qlib360_LOW22"},
        {"formula": "Div(Delay($low, 21), $close)", "name": "qlib360_LOW21"},
        {"formula": "Div(Delay($low, 20), $close)", "name": "qlib360_LOW20"},
        {"formula": "Div(Delay($low, 19), $close)", "name": "qlib360_LOW19"},
        {"formula": "Div(Delay($low, 18), $close)", "name": "qlib360_LOW18"},
        {"formula": "Div(Delay($low, 17), $close)", "name": "qlib360_LOW17"},
        {"formula": "Div(Delay($low, 16), $close)", "name": "qlib360_LOW16"},
        {"formula": "Div(Delay($low, 15), $close)", "name": "qlib360_LOW15"},
        {"formula": "Div(Delay($low, 14), $close)", "name": "qlib360_LOW14"},
        {"formula": "Div(Delay($low, 13), $close)", "name": "qlib360_LOW13"},
        {"formula": "Div(Delay($low, 12), $close)", "name": "qlib360_LOW12"},
        {"formula": "Div(Delay($low, 11), $close)", "name": "qlib360_LOW11"},
        {"formula": "Div(Delay($low, 10), $close)", "name": "qlib360_LOW10"},
        {"formula": "Div(Delay($low, 9), $close)", "name": "qlib360_LOW9"},
        {"formula": "Div(Delay($low, 8), $close)", "name": "qlib360_LOW8"},
        {"formula": "Div(Delay($low, 7), $close)", "name": "qlib360_LOW7"},
        {"formula": "Div(Delay($low, 6), $close)", "name": "qlib360_LOW6"},
        {"formula": "Div(Delay($low, 5), $close)", "name": "qlib360_LOW5"},
        {"formula": "Div(Delay($low, 4), $close)", "name": "qlib360_LOW4"},
        {"formula": "Div(Delay($low, 3), $close)", "name": "qlib360_LOW3"},
        {"formula": "Div(Delay($low, 2), $close)", "name": "qlib360_LOW2"},
        {"formula": "Div(Delay($low, 1), $close)", "name": "qlib360_LOW1"},
        {"formula": "Div($low, $close)", "name": "qlib360_LOW0"},
        {"formula": "Div(Delay($vwap, 59), $close)", "name": "qlib360_VWAP59"},
        {"formula": "Div(Delay($vwap, 58), $close)", "name": "qlib360_VWAP58"},
        {"formula": "Div(Delay($vwap, 57), $close)", "name": "qlib360_VWAP57"},
        {"formula": "Div(Delay($vwap, 56), $close)", "name": "qlib360_VWAP56"},
        {"formula": "Div(Delay($vwap, 55), $close)", "name": "qlib360_VWAP55"},
        {"formula": "Div(Delay($vwap, 54), $close)", "name": "qlib360_VWAP54"},
        {"formula": "Div(Delay($vwap, 53), $close)", "name": "qlib360_VWAP53"},
        {"formula": "Div(Delay($vwap, 52), $close)", "name": "qlib360_VWAP52"},
        {"formula": "Div(Delay($vwap, 51), $close)", "name": "qlib360_VWAP51"},
        {"formula": "Div(Delay($vwap, 50), $close)", "name": "qlib360_VWAP50"},
        {"formula": "Div(Delay($vwap, 49), $close)", "name": "qlib360_VWAP49"},
        {"formula": "Div(Delay($vwap, 48), $close)", "name": "qlib360_VWAP48"},
        {"formula": "Div(Delay($vwap, 47), $close)", "name": "qlib360_VWAP47"},
        {"formula": "Div(Delay($vwap, 46), $close)", "name": "qlib360_VWAP46"},
        {"formula": "Div(Delay($vwap, 45), $close)", "name": "qlib360_VWAP45"},
        {"formula": "Div(Delay($vwap, 44), $close)", "name": "qlib360_VWAP44"},
        {"formula": "Div(Delay($vwap, 43), $close)", "name": "qlib360_VWAP43"},
        {"formula": "Div(Delay($vwap, 42), $close)", "name": "qlib360_VWAP42"},
        {"formula": "Div(Delay($vwap, 41), $close)", "name": "qlib360_VWAP41"},
        {"formula": "Div(Delay($vwap, 40), $close)", "name": "qlib360_VWAP40"},
        {"formula": "Div(Delay($vwap, 39), $close)", "name": "qlib360_VWAP39"},
        {"formula": "Div(Delay($vwap, 38), $close)", "name": "qlib360_VWAP38"},
        {"formula": "Div(Delay($vwap, 37), $close)", "name": "qlib360_VWAP37"},
        {"formula": "Div(Delay($vwap, 36), $close)", "name": "qlib360_VWAP36"},
        {"formula": "Div(Delay($vwap, 35), $close)", "name": "qlib360_VWAP35"},
        {"formula": "Div(Delay($vwap, 34), $close)", "name": "qlib360_VWAP34"},
        {"formula": "Div(Delay($vwap, 33), $close)", "name": "qlib360_VWAP33"},
        {"formula": "Div(Delay($vwap, 32), $close)", "name": "qlib360_VWAP32"},
        {"formula": "Div(Delay($vwap, 31), $close)", "name": "qlib360_VWAP31"},
        {"formula": "Div(Delay($vwap, 30), $close)", "name": "qlib360_VWAP30"},
        {"formula": "Div(Delay($vwap, 29), $close)", "name": "qlib360_VWAP29"},
        {"formula": "Div(Delay($vwap, 28), $close)", "name": "qlib360_VWAP28"},
        {"formula": "Div(Delay($vwap, 27), $close)", "name": "qlib360_VWAP27"},
        {"formula": "Div(Delay($vwap, 26), $close)", "name": "qlib360_VWAP26"},
        {"formula": "Div(Delay($vwap, 25), $close)", "name": "qlib360_VWAP25"},
        {"formula": "Div(Delay($vwap, 24), $close)", "name": "qlib360_VWAP24"},
        {"formula": "Div(Delay($vwap, 23), $close)", "name": "qlib360_VWAP23"},
        {"formula": "Div(Delay($vwap, 22), $close)", "name": "qlib360_VWAP22"},
        {"formula": "Div(Delay($vwap, 21), $close)", "name": "qlib360_VWAP21"},
        {"formula": "Div(Delay($vwap, 20), $close)", "name": "qlib360_VWAP20"},
        {"formula": "Div(Delay($vwap, 19), $close)", "name": "qlib360_VWAP19"},
        {"formula": "Div(Delay($vwap, 18), $close)", "name": "qlib360_VWAP18"},
        {"formula": "Div(Delay($vwap, 17), $close)", "name": "qlib360_VWAP17"},
        {"formula": "Div(Delay($vwap, 16), $close)", "name": "qlib360_VWAP16"},
        {"formula": "Div(Delay($vwap, 15), $close)", "name": "qlib360_VWAP15"},
        {"formula": "Div(Delay($vwap, 14), $close)", "name": "qlib360_VWAP14"},
        {"formula": "Div(Delay($vwap, 13), $close)", "name": "qlib360_VWAP13"},
        {"formula": "Div(Delay($vwap, 12), $close)", "name": "qlib360_VWAP12"},
        {"formula": "Div(Delay($vwap, 11), $close)", "name": "qlib360_VWAP11"},
        {"formula": "Div(Delay($vwap, 10), $close)", "name": "qlib360_VWAP10"},
        {"formula": "Div(Delay($vwap, 9), $close)", "name": "qlib360_VWAP9"},
        {"formula": "Div(Delay($vwap, 8), $close)", "name": "qlib360_VWAP8"},
        {"formula": "Div(Delay($vwap, 7), $close)", "name": "qlib360_VWAP7"},
        {"formula": "Div(Delay($vwap, 6), $close)", "name": "qlib360_VWAP6"},
        {"formula": "Div(Delay($vwap, 5), $close)", "name": "qlib360_VWAP5"},
        {"formula": "Div(Delay($vwap, 4), $close)", "name": "qlib360_VWAP4"},
        {"formula": "Div(Delay($vwap, 3), $close)", "name": "qlib360_VWAP3"},
        {"formula": "Div(Delay($vwap, 2), $close)", "name": "qlib360_VWAP2"},
        {"formula": "Div(Delay($vwap, 1), $close)", "name": "qlib360_VWAP1"},
        {"formula": "Div($vwap, $close)", "name": "qlib360_VWAP0"},
        {"formula": "Div(Delay($volume, 59), Add($volume, 1e-12))", "name": "qlib360_VOLUME59"},
        {"formula": "Div(Delay($volume, 58), Add($volume, 1e-12))", "name": "qlib360_VOLUME58"},
        {"formula": "Div(Delay($volume, 57), Add($volume, 1e-12))", "name": "qlib360_VOLUME57"},
        {"formula": "Div(Delay($volume, 56), Add($volume, 1e-12))", "name": "qlib360_VOLUME56"},
        {"formula": "Div(Delay($volume, 55), Add($volume, 1e-12))", "name": "qlib360_VOLUME55"},
        {"formula": "Div(Delay($volume, 54), Add($volume, 1e-12))", "name": "qlib360_VOLUME54"},
        {"formula": "Div(Delay($volume, 53), Add($volume, 1e-12))", "name": "qlib360_VOLUME53"},
        {"formula": "Div(Delay($volume, 52), Add($volume, 1e-12))", "name": "qlib360_VOLUME52"},
        {"formula": "Div(Delay($volume, 51), Add($volume, 1e-12))", "name": "qlib360_VOLUME51"},
        {"formula": "Div(Delay($volume, 50), Add($volume, 1e-12))", "name": "qlib360_VOLUME50"},
        {"formula": "Div(Delay($volume, 49), Add($volume, 1e-12))", "name": "qlib360_VOLUME49"},
        {"formula": "Div(Delay($volume, 48), Add($volume, 1e-12))", "name": "qlib360_VOLUME48"},
        {"formula": "Div(Delay($volume, 47), Add($volume, 1e-12))", "name": "qlib360_VOLUME47"},
        {"formula": "Div(Delay($volume, 46), Add($volume, 1e-12))", "name": "qlib360_VOLUME46"},
        {"formula": "Div(Delay($volume, 45), Add($volume, 1e-12))", "name": "qlib360_VOLUME45"},
        {"formula": "Div(Delay($volume, 44), Add($volume, 1e-12))", "name": "qlib360_VOLUME44"},
        {"formula": "Div(Delay($volume, 43), Add($volume, 1e-12))", "name": "qlib360_VOLUME43"},
        {"formula": "Div(Delay($volume, 42), Add($volume, 1e-12))", "name": "qlib360_VOLUME42"},
        {"formula": "Div(Delay($volume, 41), Add($volume, 1e-12))", "name": "qlib360_VOLUME41"},
        {"formula": "Div(Delay($volume, 40), Add($volume, 1e-12))", "name": "qlib360_VOLUME40"},
        {"formula": "Div(Delay($volume, 39), Add($volume, 1e-12))", "name": "qlib360_VOLUME39"},
        {"formula": "Div(Delay($volume, 38), Add($volume, 1e-12))", "name": "qlib360_VOLUME38"},
        {"formula": "Div(Delay($volume, 37), Add($volume, 1e-12))", "name": "qlib360_VOLUME37"},
        {"formula": "Div(Delay($volume, 36), Add($volume, 1e-12))", "name": "qlib360_VOLUME36"},
        {"formula": "Div(Delay($volume, 35), Add($volume, 1e-12))", "name": "qlib360_VOLUME35"},
        {"formula": "Div(Delay($volume, 34), Add($volume, 1e-12))", "name": "qlib360_VOLUME34"},
        {"formula": "Div(Delay($volume, 33), Add($volume, 1e-12))", "name": "qlib360_VOLUME33"},
        {"formula": "Div(Delay($volume, 32), Add($volume, 1e-12))", "name": "qlib360_VOLUME32"},
        {"formula": "Div(Delay($volume, 31), Add($volume, 1e-12))", "name": "qlib360_VOLUME31"},
        {"formula": "Div(Delay($volume, 30), Add($volume, 1e-12))", "name": "qlib360_VOLUME30"},
        {"formula": "Div(Delay($volume, 29), Add($volume, 1e-12))", "name": "qlib360_VOLUME29"},
        {"formula": "Div(Delay($volume, 28), Add($volume, 1e-12))", "name": "qlib360_VOLUME28"},
        {"formula": "Div(Delay($volume, 27), Add($volume, 1e-12))", "name": "qlib360_VOLUME27"},
        {"formula": "Div(Delay($volume, 26), Add($volume, 1e-12))", "name": "qlib360_VOLUME26"},
        {"formula": "Div(Delay($volume, 25), Add($volume, 1e-12))", "name": "qlib360_VOLUME25"},
        {"formula": "Div(Delay($volume, 24), Add($volume, 1e-12))", "name": "qlib360_VOLUME24"},
        {"formula": "Div(Delay($volume, 23), Add($volume, 1e-12))", "name": "qlib360_VOLUME23"},
        {"formula": "Div(Delay($volume, 22), Add($volume, 1e-12))", "name": "qlib360_VOLUME22"},
        {"formula": "Div(Delay($volume, 21), Add($volume, 1e-12))", "name": "qlib360_VOLUME21"},
        {"formula": "Div(Delay($volume, 20), Add($volume, 1e-12))", "name": "qlib360_VOLUME20"},
        {"formula": "Div(Delay($volume, 19), Add($volume, 1e-12))", "name": "qlib360_VOLUME19"},
        {"formula": "Div(Delay($volume, 18), Add($volume, 1e-12))", "name": "qlib360_VOLUME18"},
        {"formula": "Div(Delay($volume, 17), Add($volume, 1e-12))", "name": "qlib360_VOLUME17"},
        {"formula": "Div(Delay($volume, 16), Add($volume, 1e-12))", "name": "qlib360_VOLUME16"},
        {"formula": "Div(Delay($volume, 15), Add($volume, 1e-12))", "name": "qlib360_VOLUME15"},
        {"formula": "Div(Delay($volume, 14), Add($volume, 1e-12))", "name": "qlib360_VOLUME14"},
        {"formula": "Div(Delay($volume, 13), Add($volume, 1e-12))", "name": "qlib360_VOLUME13"},
        {"formula": "Div(Delay($volume, 12), Add($volume, 1e-12))", "name": "qlib360_VOLUME12"},
        {"formula": "Div(Delay($volume, 11), Add($volume, 1e-12))", "name": "qlib360_VOLUME11"},
        {"formula": "Div(Delay($volume, 10), Add($volume, 1e-12))", "name": "qlib360_VOLUME10"},
        {"formula": "Div(Delay($volume, 9), Add($volume, 1e-12))", "name": "qlib360_VOLUME9"},
        {"formula": "Div(Delay($volume, 8), Add($volume, 1e-12))", "name": "qlib360_VOLUME8"},
        {"formula": "Div(Delay($volume, 7), Add($volume, 1e-12))", "name": "qlib360_VOLUME7"},
        {"formula": "Div(Delay($volume, 6), Add($volume, 1e-12))", "name": "qlib360_VOLUME6"},
        {"formula": "Div(Delay($volume, 5), Add($volume, 1e-12))", "name": "qlib360_VOLUME5"},
        {"formula": "Div(Delay($volume, 4), Add($volume, 1e-12))", "name": "qlib360_VOLUME4"},
        {"formula": "Div(Delay($volume, 3), Add($volume, 1e-12))", "name": "qlib360_VOLUME3"},
        {"formula": "Div(Delay($volume, 2), Add($volume, 1e-12))", "name": "qlib360_VOLUME2"},
        {"formula": "Div(Delay($volume, 1), Add($volume, 1e-12))", "name": "qlib360_VOLUME1"},
        {"formula": "Div($volume, Add($volume, 1e-12))", "name": "qlib360_VOLUME0"},
    ]

    variants: list[CandidateEntry] = []

    # add 'category' = 'qlib alpha158' to QLIB_ALPHA158_LIST
    for alpha in qlib_alpha360:
        variants.append(
            CandidateEntry(
                name=alpha["name"].lower(),
                formula=to_prefix_dsl(alpha["formula"]),
                category="qlib alpha360",
            )
        )

    # print(QLIB_ALPHA158_LIST)
    return variants
